/**
 * Dedicated Database for Find Business (Smart Ideator)
 * Features 58 real-world commercial models with localized viability scores,
 * priority layering (actual verified models at top), and mock on/off flags.
 */

export interface BusinessOpportunity {
  id: string;
  name: string;
  category: 'food' | 'tech' | 'fitness' | 'retail' | 'education';
  emoji: string;
  startupCost: number;
  monthlyRevenue: number;
  roiMonths: number;
  competition: 'Low' | 'Medium' | 'High';
  competitionScore: number;
  description: string;
  bestSuitedFor: string;
  minAreaSqft: number;
  targetMarginPercent: number;
  recommendedCities: string[];
  cityViabilityScores: Record<string, number>;
  isFranchise?: boolean;
  franchiseBrand?: string;
  applyUrl?: string;
  isOfficial?: boolean;
  sourceBadge?: string;
  isActualData?: boolean;
}

export type ExtendedBusinessOpportunity = BusinessOpportunity;

export const BUSINESS_FINDER_FLAGS = {
  USE_MOCK_FALLBACK: true,
  PRIORITIZE_ACTUAL: true,
};

/**
 * Actual Live/Government-Subsidized Opportunities (Priority 1)
 */
export const ACTUAL_LIVE_OPPORTUNITIES: BusinessOpportunity[] = [
  // --- TECH & ELECTRONICS ---
  {
    id: 'gov-pmegp-ev',
    name: 'Govt Subsidized EV Charging & Battery Swap Hub',
    category: 'tech',
    emoji: '⚡',
    startupCost: 750000,
    monthlyRevenue: 280000,
    roiMonths: 8,
    competition: 'Low',
    competitionScore: 9.4,
    description: 'Government subsidized 2/3-wheeler fast charging & swappable battery clinic backed by 35% PMEGP capital subsidy.',
    bestSuitedFor: 'Entrepreneurs leveraging 35% PMEGP capital subsidy and green mobility demand.',
    minAreaSqft: 400,
    targetMarginPercent: 55,
    recommendedCities: ['Jaipur', 'Bengaluru', 'Delhi', 'Pune', 'Mumbai', 'Chennai'],
    cityViabilityScores: { Jaipur: 9.6, Bengaluru: 9.7, Delhi: 9.8, Mumbai: 9.5, Pune: 9.4, Chennai: 9.2 },
    isOfficial: true,
    sourceBadge: 'Govt PMEGP 35% Subsidy',
    applyUrl: 'https://www.jansamarth.in/',
    isActualData: true,
  },
  {
    id: 'actual-lenskart',
    name: 'Lenskart Optical & Eyewear Tech Clinic',
    category: 'tech',
    emoji: '👓',
    startupCost: 2800000,
    monthlyRevenue: 750000,
    roiMonths: 18,
    competition: 'Medium',
    competitionScore: 9.3,
    description: 'Omnichannel eyewear retail store with robotic lens cutting and AI prescription tech backed by leading national eyewear brand.',
    bestSuitedFor: 'Retail investors wanting tech-driven inventory support and strong customer recall.',
    minAreaSqft: 450,
    targetMarginPercent: 48,
    recommendedCities: ['Bengaluru', 'Delhi', 'Jaipur', 'Pune', 'Mumbai', 'Chennai'],
    cityViabilityScores: { Bengaluru: 9.8, Delhi: 9.7, Jaipur: 9.5, Mumbai: 9.6, Pune: 9.4, Chennai: 9.3 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Lenskart',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://www.lenskart.com/franchise',
    isActualData: true,
  },
  {
    id: 'actual-cashify',
    name: 'Cashify Gadget Buyback & Screen Care Kiosk',
    category: 'tech',
    emoji: '📱',
    startupCost: 850000,
    monthlyRevenue: 290000,
    roiMonths: 10,
    competition: 'Low',
    competitionScore: 9.1,
    description: 'High-margin smartphone trade-in, certified refurbished device sales, and express on-spot repair hub.',
    bestSuitedFor: 'High footfall mall or transit corridor operators wanting rapid cash turns.',
    minAreaSqft: 180,
    targetMarginPercent: 52,
    recommendedCities: ['Delhi', 'Bengaluru', 'Mumbai', 'Pune', 'Jaipur', 'Chennai'],
    cityViabilityScores: { Delhi: 9.6, Bengaluru: 9.5, Mumbai: 9.5, Pune: 9.2, Jaipur: 9.1, Chennai: 9.0 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Cashify',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://www.cashify.in/franchise',
    isActualData: true,
  },
  {
    id: 'gov-pmkvy-electronics',
    name: 'Skill India / PMKVY Certified Electronics Service Lab',
    category: 'tech',
    emoji: '🛠️',
    startupCost: 240000,
    monthlyRevenue: 125000,
    roiMonths: 7,
    competition: 'Low',
    competitionScore: 9.0,
    description: 'Government Skill India certified PCB repair and micro-soldering service center with subsidized tooling grants.',
    bestSuitedFor: 'Diploma holders and technicians seeking certified enterprise repair tie-ups.',
    minAreaSqft: 200,
    targetMarginPercent: 65,
    recommendedCities: ['Jaipur', 'Pune', 'Bengaluru', 'Delhi', 'Chennai', 'Mumbai'],
    cityViabilityScores: { Jaipur: 9.4, Pune: 9.3, Bengaluru: 9.2, Delhi: 9.1, Chennai: 9.0, Mumbai: 8.9 },
    isOfficial: true,
    sourceBadge: 'Skill India MSME Grant',
    applyUrl: 'https://www.skillindia.gov.in/',
    isActualData: true,
  },

  // --- FOOD & BEVERAGE ---
  {
    id: 'actual-teapost',
    name: 'Tea Post Chai & Desi Snack Cafe',
    category: 'food',
    emoji: '☕',
    startupCost: 1200000,
    monthlyRevenue: 380000,
    roiMonths: 12,
    competition: 'Medium',
    competitionScore: 9.4,
    description: 'Established 300+ outlet quick-service tea and snack cafe format with high margins on specialty brew and maska buns.',
    bestSuitedFor: 'Founders targeting youth and office cluster corridors with steady repeat footfall.',
    minAreaSqft: 350,
    targetMarginPercent: 62,
    recommendedCities: ['Jaipur', 'Pune', 'Bengaluru', 'Mumbai', 'Delhi', 'Chennai'],
    cityViabilityScores: { Jaipur: 9.8, Pune: 9.6, Bengaluru: 9.5, Mumbai: 9.3, Delhi: 9.4, Chennai: 9.1 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Tea Post',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://teapost.in/franchise/',
    isActualData: true,
  },
  {
    id: 'actual-chaipoint',
    name: 'Chai Point Express Transit Kiosk',
    category: 'food',
    emoji: '🫖',
    startupCost: 1500000,
    monthlyRevenue: 480000,
    roiMonths: 14,
    competition: 'Medium',
    competitionScore: 9.2,
    description: 'Tech-enabled corporate and transit chai cafe format equipped with automated brewing and high-ticket bakery pairings.',
    bestSuitedFor: 'Tech parks, metro interchange, and premium commercial high streets.',
    minAreaSqft: 250,
    targetMarginPercent: 64,
    recommendedCities: ['Bengaluru', 'Delhi', 'Mumbai', 'Pune', 'Hyderabad', 'Chennai'],
    cityViabilityScores: { Bengaluru: 9.9, Delhi: 9.7, Mumbai: 9.6, Pune: 9.5, Chennai: 9.2, Jaipur: 9.0 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Chai Point',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://chaipoint.com/franchise/',
    isActualData: true,
  },
  {
    id: 'actual-wowmomo',
    name: 'Wow! Momo Food Court & High Street Kiosk',
    category: 'food',
    emoji: '🥟',
    startupCost: 1800000,
    monthlyRevenue: 560000,
    roiMonths: 15,
    competition: 'Low',
    competitionScore: 9.5,
    description: 'National QSR sensation with 600+ outlets serving frozen-to-steamed momos, burger momos, and pan-fried platters.',
    bestSuitedFor: 'High footfall shopping malls, market plazas, and cinema corridors.',
    minAreaSqft: 250,
    targetMarginPercent: 68,
    recommendedCities: ['Delhi', 'Bengaluru', 'Mumbai', 'Jaipur', 'Pune', 'Chennai'],
    cityViabilityScores: { Delhi: 9.9, Bengaluru: 9.8, Mumbai: 9.7, Jaipur: 9.5, Pune: 9.4, Chennai: 9.3 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Wow! Momo',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://wowmomo.com/franchise',
    isActualData: true,
  },
  {
    id: 'gov-pmmy-cloud-kitchen',
    name: 'Mudra-Assisted Millet & Healthy Food Cloud Kitchen',
    category: 'food',
    emoji: '🥗',
    startupCost: 350000,
    monthlyRevenue: 160000,
    roiMonths: 7,
    competition: 'Low',
    competitionScore: 9.1,
    description: 'Zero-collateral MUDRA Tarun backed delivery-first commercial kitchen specializing in high-margin millet bowls.',
    bestSuitedFor: 'Culinary founders with delivery focus and minimal physical dine-in capital requirement.',
    minAreaSqft: 250,
    targetMarginPercent: 62,
    recommendedCities: ['Bengaluru', 'Delhi', 'Jaipur', 'Pune', 'Mumbai', 'Chennai'],
    cityViabilityScores: { Bengaluru: 9.8, Jaipur: 9.1, Delhi: 9.5, Mumbai: 9.7, Pune: 9.3, Chennai: 9.0 },
    isOfficial: true,
    sourceBadge: 'MUDRA Tarun Scheme',
    applyUrl: 'https://www.jansamarth.in/',
    isActualData: true,
  },

  // --- RETAIL ---
  {
    id: 'gov-pmbjk-pharmacy',
    name: 'Pradhan Mantri Bhartiya Janaushadhi Kendra (PMBJK)',
    category: 'retail',
    emoji: '💊',
    startupCost: 250000,
    monthlyRevenue: 195000,
    roiMonths: 6,
    competition: 'Low',
    competitionScore: 9.7,
    description: 'Government subsidized generic medicine pharmacy with ₹2.5 Lakhs financial incentive and 20% trade margin.',
    bestSuitedFor: 'Pharmacists and entrepreneurs seeking guaranteed government health scheme support.',
    minAreaSqft: 120,
    targetMarginPercent: 25,
    recommendedCities: ['Jaipur', 'Delhi', 'Pune', 'Bengaluru', 'Chennai', 'Mumbai'],
    cityViabilityScores: { Jaipur: 9.8, Delhi: 9.7, Pune: 9.5, Bengaluru: 9.4, Chennai: 9.4, Mumbai: 9.3 },
    isOfficial: true,
    sourceBadge: 'Govt PMBJK Scheme',
    applyUrl: 'https://janaushadhi.gov.in/',
    isActualData: true,
  },
  {
    id: 'actual-amul-parlour',
    name: 'Amul Preferred Outlet & Ice Cream Parlour',
    category: 'retail',
    emoji: '🍦',
    startupCost: 450000,
    monthlyRevenue: 220000,
    roiMonths: 8,
    competition: 'Low',
    competitionScore: 9.6,
    description: 'Zero royalty dairy parlour backed by India’s largest dairy cooperative with assured daily inventory delivery.',
    bestSuitedFor: 'Corner shops near residential clusters, gardens, and school zones.',
    minAreaSqft: 200,
    targetMarginPercent: 22,
    recommendedCities: ['Jaipur', 'Bengaluru', 'Delhi', 'Pune', 'Mumbai', 'Chennai'],
    cityViabilityScores: { Jaipur: 9.8, Delhi: 9.7, Bengaluru: 9.6, Mumbai: 9.6, Pune: 9.5, Chennai: 9.2 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Amul',
    sourceBadge: 'Official Brand Network',
    applyUrl: 'https://amul.com/m/amul-preferred-outlet-and-amul-ice-cream-scooping-parlour',
    isActualData: true,
  },
  {
    id: 'actual-dtdc-courier',
    name: 'DTDC Express Courier & E-Commerce Logistics Point',
    category: 'retail',
    emoji: '📦',
    startupCost: 180000,
    monthlyRevenue: 95000,
    roiMonths: 6,
    competition: 'Low',
    competitionScore: 9.2,
    description: 'B2B and retail parcel dispatch center with verified commission structure and high corporate volume.',
    bestSuitedFor: 'Commercial markets and industrial estates with minimal retail fit-out needs.',
    minAreaSqft: 100,
    targetMarginPercent: 35,
    recommendedCities: ['Jaipur', 'Bengaluru', 'Delhi', 'Pune', 'Mumbai', 'Chennai'],
    cityViabilityScores: { Jaipur: 9.5, Bengaluru: 9.6, Delhi: 9.6, Mumbai: 9.5, Pune: 9.4, Chennai: 9.2 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'DTDC',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://www.dtdc.in/channel-partners.asp',
    isActualData: true,
  },
  {
    id: 'actual-fnp-boutique',
    name: 'Ferns N Petals (FNP) Luxury Floral & Gift Boutique',
    category: 'retail',
    emoji: '💐',
    startupCost: 1400000,
    monthlyRevenue: 340000,
    roiMonths: 14,
    competition: 'Low',
    competitionScore: 9.1,
    description: 'Premium branded gifting, floral decor, personalized cakes, and celebration retail format.',
    bestSuitedFor: 'High-income residential catchments and shopping high-streets.',
    minAreaSqft: 300,
    targetMarginPercent: 55,
    recommendedCities: ['Delhi', 'Mumbai', 'Bengaluru', 'Jaipur', 'Pune', 'Chennai'],
    cityViabilityScores: { Delhi: 9.8, Mumbai: 9.7, Bengaluru: 9.6, Jaipur: 9.3, Pune: 9.2, Chennai: 9.1 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Ferns N Petals',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://www.fnp.com/info/franchise',
    isActualData: true,
  },

  // --- FITNESS & WELLNESS ---
  {
    id: 'actual-cultfit',
    name: 'Cult.fit Gym & Functional Fitness Studio',
    category: 'fitness',
    emoji: '🏋️',
    startupCost: 3500000,
    monthlyRevenue: 980000,
    roiMonths: 18,
    competition: 'Medium',
    competitionScore: 9.5,
    description: 'Tech-integrated group workout and gym format with centralized Cult app member bookings and trainer certification.',
    bestSuitedFor: 'Tech corridors, affluent residential areas, and commercial fitness centers.',
    minAreaSqft: 2500,
    targetMarginPercent: 65,
    recommendedCities: ['Bengaluru', 'Delhi', 'Mumbai', 'Pune', 'Hyderabad', 'Jaipur'],
    cityViabilityScores: { Bengaluru: 9.9, Delhi: 9.8, Mumbai: 9.7, Pune: 9.6, Hyderabad: 9.5, Jaipur: 9.1 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Cult.fit',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://www.cult.fit/franchise',
    isActualData: true,
  },
  {
    id: 'actual-naturals-salon',
    name: 'Naturals Unisex Salon & Wellness Lounge',
    category: 'fitness',
    emoji: '✂️',
    startupCost: 2400000,
    monthlyRevenue: 620000,
    roiMonths: 15,
    competition: 'Medium',
    competitionScore: 9.4,
    description: 'Over 700+ unisex salons across India with corporate marketing support, trained staff pipelines, and FMCG retail sales.',
    bestSuitedFor: 'Urban shopping high-streets and affluent neighborhood main roads.',
    minAreaSqft: 800,
    targetMarginPercent: 58,
    recommendedCities: ['Chennai', 'Bengaluru', 'Hyderabad', 'Pune', 'Jaipur', 'Delhi'],
    cityViabilityScores: { Chennai: 9.9, Bengaluru: 9.7, Hyderabad: 9.6, Pune: 9.4, Jaipur: 9.3, Delhi: 9.2 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Naturals',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://naturals.in/franchise/',
    isActualData: true,
  },
  {
    id: 'actual-anytime-fitness',
    name: 'Anytime Fitness 24/7 Premium Express Gym',
    category: 'fitness',
    emoji: '💪',
    startupCost: 4800000,
    monthlyRevenue: 1200000,
    roiMonths: 20,
    competition: 'Low',
    competitionScore: 9.3,
    description: 'World’s largest 24-hour fitness franchise with global member reciprocal access and advanced Precor equipment.',
    bestSuitedFor: 'High-density residential hubs and corporate IT parks.',
    minAreaSqft: 3500,
    targetMarginPercent: 68,
    recommendedCities: ['Delhi', 'Mumbai', 'Bengaluru', 'Pune', 'Jaipur', 'Chennai'],
    cityViabilityScores: { Delhi: 9.8, Mumbai: 9.7, Bengaluru: 9.7, Pune: 9.5, Jaipur: 9.2, Chennai: 9.3 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Anytime Fitness',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://anytimefitness.co.in/franchise/',
    isActualData: true,
  },

  // --- EDUCATION & SKILLING ---
  {
    id: 'actual-kidzee',
    name: 'Kidzee Pre-School & Early Childhood Academy',
    category: 'education',
    emoji: '🎨',
    startupCost: 1500000,
    monthlyRevenue: 420000,
    roiMonths: 14,
    competition: 'Low',
    competitionScore: 9.6,
    description: 'Pioneer in early childhood care and education with over 2000+ verified centres backed by Zee Learn curriculum.',
    bestSuitedFor: 'Residential colonies, gated township community centres, and villa enclaves.',
    minAreaSqft: 1800,
    targetMarginPercent: 65,
    recommendedCities: ['Jaipur', 'Pune', 'Bengaluru', 'Delhi', 'Mumbai', 'Chennai'],
    cityViabilityScores: { Jaipur: 9.8, Pune: 9.7, Bengaluru: 9.6, Delhi: 9.6, Mumbai: 9.5, Chennai: 9.4 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'Kidzee',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://www.kidzee.com/franchise/',
    isActualData: true,
  },
  {
    id: 'actual-eurokids',
    name: 'EuroKids Preschool & Day Care Center',
    category: 'education',
    emoji: '🧸',
    startupCost: 1800000,
    monthlyRevenue: 490000,
    roiMonths: 15,
    competition: 'Low',
    competitionScore: 9.5,
    description: 'International early childhood education brand with 1400+ preschools and proprietary MindChamps learning pedagogy.',
    bestSuitedFor: 'High-income residential suburbs with young millennial families.',
    minAreaSqft: 2000,
    targetMarginPercent: 66,
    recommendedCities: ['Bengaluru', 'Mumbai', 'Pune', 'Delhi', 'Jaipur', 'Chennai'],
    cityViabilityScores: { Bengaluru: 9.9, Mumbai: 9.8, Pune: 9.6, Delhi: 9.5, Jaipur: 9.4, Chennai: 9.4 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'EuroKids',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://www.eurokidsindia.com/franchise/',
    isActualData: true,
  },
  {
    id: 'actual-niit-digital',
    name: 'NIIT Digital Learning & IT Certification Academy',
    category: 'education',
    emoji: '💻',
    startupCost: 1200000,
    monthlyRevenue: 340000,
    roiMonths: 12,
    competition: 'Low',
    competitionScore: 9.2,
    description: 'Software engineering, data analytics, and cloud skills academy with verified employer placement partnerships.',
    bestSuitedFor: 'College town hubs, transit corridors, and coaching districts.',
    minAreaSqft: 1000,
    targetMarginPercent: 60,
    recommendedCities: ['Jaipur', 'Pune', 'Bengaluru', 'Delhi', 'Chennai', 'Mumbai'],
    cityViabilityScores: { Jaipur: 9.7, Pune: 9.6, Bengaluru: 9.5, Delhi: 9.4, Chennai: 9.3, Mumbai: 9.2 },
    isOfficial: true,
    isFranchise: true,
    franchiseBrand: 'NIIT',
    sourceBadge: 'Official Franchise Network',
    applyUrl: 'https://www.niit.com/india/training/franchise',
    isActualData: true,
  },
];

export const EXTENDED_BUSINESS_OPPORTUNITIES: ExtendedBusinessOpportunity[] = [
  {
    "id": "tech-1",
    "name": "Express Mobile & Tech Care Lab",
    "category": "tech",
    "emoji": "\ud83d\udcf1",
    "startupCost": 180000,
    "monthlyRevenue": 95000,
    "roiMonths": 7,
    "competition": "Low",
    "competitionScore": 8.9,
    "description": "Rapid chip-level smartphone, tablet and motherboard repair clinic with OEM-certified accessories.",
    "bestSuitedFor": "Technical technicians and gadget enthusiasts wanting swift breakeven.",
    "minAreaSqft": 150,
    "targetMarginPercent": 52,
    "recommendedCities": [
      "Bengaluru",
      "Delhi",
      "Jaipur",
      "Pune",
      "Mumbai",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.6,
      "Delhi": 9.2,
      "Pune": 9.4,
      "Jaipur": 8.8,
      "Mumbai": 9.0,
      "Chennai": 9.1
    }
  },
  {
    "id": "tech-2",
    "name": "EV Two-Wheeler Battery & Diagnostics Hub",
    "category": "tech",
    "emoji": "\u26a1",
    "startupCost": 450000,
    "monthlyRevenue": 185000,
    "roiMonths": 9,
    "competition": "Low",
    "competitionScore": 9.4,
    "description": "Authorized multi-brand electric scooter battery health check, swappable power pack and brake service.",
    "bestSuitedFor": "Automotive electrical specialists tapping the rapid clean mobility boom.",
    "minAreaSqft": 350,
    "targetMarginPercent": 48,
    "recommendedCities": [
      "Bengaluru",
      "Delhi",
      "Jaipur",
      "Pune",
      "Chennai",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.8,
      "Jaipur": 9.5,
      "Delhi": 9.3,
      "Pune": 9.4,
      "Chennai": 9.2,
      "Mumbai": 8.9
    }
  },
  {
    "id": "tech-3",
    "name": "Custom Gaming Rig & Workstation Studio",
    "category": "tech",
    "emoji": "\ud83d\udcbb",
    "startupCost": 380000,
    "monthlyRevenue": 160000,
    "roiMonths": 10,
    "competition": "Low",
    "competitionScore": 8.7,
    "description": "High-performance PC assembly, liquid cooling installation and GPU thermal re-pasting station.",
    "bestSuitedFor": "Gamers, video editors and PC builders serving content creators and studios.",
    "minAreaSqft": 250,
    "targetMarginPercent": 38,
    "recommendedCities": [
      "Bengaluru",
      "Pune",
      "Delhi",
      "Mumbai",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.7,
      "Pune": 9.5,
      "Delhi": 9.0,
      "Mumbai": 9.2,
      "Jaipur": 8.4,
      "Chennai": 8.9
    }
  },
  {
    "id": "tech-4",
    "name": "Smart Home & IoT Automation Agency",
    "category": "tech",
    "emoji": "\ud83c\udfe0",
    "startupCost": 260000,
    "monthlyRevenue": 140000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 9.0,
    "description": "Consulting and installation center for smart lighting, video doorbells, smart locks and home sensors.",
    "bestSuitedFor": "Systems integrators and electrical engineers partnering with modern interior designers.",
    "minAreaSqft": 200,
    "targetMarginPercent": 45,
    "recommendedCities": [
      "Bengaluru",
      "Delhi",
      "Mumbai",
      "Jaipur",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.5,
      "Mumbai": 9.4,
      "Delhi": 9.3,
      "Jaipur": 9.1,
      "Pune": 9.0,
      "Chennai": 8.7
    }
  },
  {
    "id": "tech-5",
    "name": "Drone Assembly & Precision Repair Lab",
    "category": "tech",
    "emoji": "\ud83d\udef8",
    "startupCost": 520000,
    "monthlyRevenue": 210000,
    "roiMonths": 11,
    "competition": "Low",
    "competitionScore": 9.2,
    "description": "Commercial and agricultural UAV drone maintenance, camera gimbal calibration and motor replacement.",
    "bestSuitedFor": "Aerospace or electronics hobbyists capturing surveying and wedding drone markets.",
    "minAreaSqft": 300,
    "targetMarginPercent": 44,
    "recommendedCities": [
      "Jaipur",
      "Bengaluru",
      "Pune",
      "Delhi",
      "Chennai",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.6,
      "Bengaluru": 9.4,
      "Pune": 9.2,
      "Delhi": 9.0,
      "Chennai": 8.8,
      "Mumbai": 8.6
    }
  },
  {
    "id": "tech-6",
    "name": "Refurbished Premium Laptops & Tech Resale",
    "category": "tech",
    "emoji": "\ud83d\udda5\ufe0f",
    "startupCost": 420000,
    "monthlyRevenue": 190000,
    "roiMonths": 8,
    "competition": "Medium",
    "competitionScore": 8.3,
    "description": "Quality-tested enterprise laptops (ThinkPad, Dell, MacBook) sold with warranty and upgrade services.",
    "bestSuitedFor": "Sellers serving students, remote freelancers and cost-conscious startup employees.",
    "minAreaSqft": 220,
    "targetMarginPercent": 35,
    "recommendedCities": [
      "Pune",
      "Bengaluru",
      "Delhi",
      "Jaipur",
      "Chennai",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Pune": 9.6,
      "Bengaluru": 9.5,
      "Delhi": 9.1,
      "Jaipur": 9.0,
      "Chennai": 8.9,
      "Mumbai": 8.8
    }
  },
  {
    "id": "tech-7",
    "name": "3D Printing & Industrial Prototyping Workshop",
    "category": "tech",
    "emoji": "\ud83d\udda8\ufe0f",
    "startupCost": 340000,
    "monthlyRevenue": 145000,
    "roiMonths": 9,
    "competition": "Low",
    "competitionScore": 8.9,
    "description": "FDM and resin 3D printing rapid prototyping service for design engineering, gifts and architecture models.",
    "bestSuitedFor": "Makers and CAD modelers seeking business-to-business repeat contracts.",
    "minAreaSqft": 200,
    "targetMarginPercent": 55,
    "recommendedCities": [
      "Bengaluru",
      "Pune",
      "Chennai",
      "Delhi",
      "Mumbai",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.6,
      "Pune": 9.4,
      "Chennai": 9.2,
      "Delhi": 8.9,
      "Mumbai": 8.8,
      "Jaipur": 8.3
    }
  },
  {
    "id": "tech-8",
    "name": "Solar Rooftop & Inverter Diagnostic Desk",
    "category": "tech",
    "emoji": "\u2600\ufe0f",
    "startupCost": 290000,
    "monthlyRevenue": 130000,
    "roiMonths": 10,
    "competition": "Low",
    "competitionScore": 8.8,
    "description": "Residential solar panel efficiency audits, net-metering consultancy and inverter board repairs.",
    "bestSuitedFor": "Renewable energy technicians tapping rooftop solar subsidy policies.",
    "minAreaSqft": 180,
    "targetMarginPercent": 42,
    "recommendedCities": [
      "Jaipur",
      "Delhi",
      "Pune",
      "Chennai",
      "Bengaluru",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.8,
      "Delhi": 9.2,
      "Pune": 9.1,
      "Chennai": 9.0,
      "Bengaluru": 8.7,
      "Mumbai": 8.4
    }
  },
  {
    "id": "tech-9",
    "name": "CCTV, Biometric & Perimeter Security Hub",
    "category": "tech",
    "emoji": "\ud83d\udd12",
    "startupCost": 210000,
    "monthlyRevenue": 115000,
    "roiMonths": 7,
    "competition": "Medium",
    "competitionScore": 8.2,
    "description": "Turnkey commercial CCTV installation, biometric attendance machines and smart cloud NVR setups.",
    "bestSuitedFor": "Contractors catering to commercial offices, warehouses, clinics and housing societies.",
    "minAreaSqft": 160,
    "targetMarginPercent": 40,
    "recommendedCities": [
      "Delhi",
      "Jaipur",
      "Bengaluru",
      "Mumbai",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Delhi": 9.4,
      "Jaipur": 9.3,
      "Bengaluru": 9.1,
      "Mumbai": 9.0,
      "Pune": 8.9,
      "Chennai": 8.8
    }
  },
  {
    "id": "tech-10",
    "name": "Data Recovery & Chip Micro-Soldering Specialist",
    "category": "tech",
    "emoji": "\ud83d\udcbe",
    "startupCost": 310000,
    "monthlyRevenue": 150000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 9.3,
    "description": "Clean-bench crashed SSD/HDD data retrieval and high-precision micro-soldering on damaged logic boards.",
    "bestSuitedFor": "Specialized electronics hardware experts commanding premium ticket pricing.",
    "minAreaSqft": 140,
    "targetMarginPercent": 65,
    "recommendedCities": [
      "Bengaluru",
      "Mumbai",
      "Delhi",
      "Chennai",
      "Pune",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.7,
      "Mumbai": 9.5,
      "Delhi": 9.3,
      "Chennai": 9.1,
      "Pune": 9.0,
      "Jaipur": 8.6
    }
  },
  {
    "id": "tech-11",
    "name": "DTDC Express Courier & Logistics Hub",
    "category": "tech",
    "emoji": "\ud83d\udce6",
    "startupCost": 200000,
    "monthlyRevenue": 110000,
    "roiMonths": 7,
    "competition": "Medium",
    "competitionScore": 8.5,
    "description": "Domestic & international parcel express center with integrated tracking and B2B eCommerce pickup.",
    "bestSuitedFor": "Entrepreneurs seeking reliable institutional logistics franchise backing.",
    "minAreaSqft": 180,
    "targetMarginPercent": 35,
    "isFranchise": true,
    "franchiseBrand": "DTDC",
    "applyUrl": "https://www.dtdc.in/channel_partners.asp",
    "isOfficial": true,
    "recommendedCities": [
      "Bengaluru",
      "Jaipur",
      "Delhi",
      "Mumbai",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.3,
      "Jaipur": 9.4,
      "Delhi": 9.2,
      "Mumbai": 9.1,
      "Pune": 9.0,
      "Chennai": 8.9
    }
  },
  {
    "id": "tech-12",
    "name": "Digital Signage & LED Video Wall Solutions",
    "category": "tech",
    "emoji": "\ud83d\udca1",
    "startupCost": 480000,
    "monthlyRevenue": 200000,
    "roiMonths": 10,
    "competition": "Low",
    "competitionScore": 8.6,
    "description": "High-brightness retail LED display panels, restaurant digital menu boards and cloud content scheduling.",
    "bestSuitedFor": "AV system integrators targeting modernizing retail high streets and banquet halls.",
    "minAreaSqft": 250,
    "targetMarginPercent": 42,
    "recommendedCities": [
      "Delhi",
      "Mumbai",
      "Bengaluru",
      "Jaipur",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Delhi": 9.5,
      "Mumbai": 9.4,
      "Bengaluru": 9.2,
      "Jaipur": 9.1,
      "Pune": 8.8,
      "Chennai": 8.7
    }
  },
  {
    "id": "food-1",
    "name": "Fresh Cold-Pressed Juice & Wellness Bar",
    "category": "food",
    "emoji": "\ud83e\udd64",
    "startupCost": 220000,
    "monthlyRevenue": 120000,
    "roiMonths": 8,
    "competition": "Medium",
    "competitionScore": 8.0,
    "description": "Raw unpasteurized cold-pressed fruit juices, ginger immunity shots and fresh seasonal fruit bowls.",
    "bestSuitedFor": "Health-conscious operators stationed near jogging parks, gyms, or corporate high streets.",
    "minAreaSqft": 140,
    "targetMarginPercent": 58,
    "recommendedCities": [
      "Bengaluru",
      "Mumbai",
      "Delhi",
      "Pune",
      "Chennai",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.4,
      "Mumbai": 9.5,
      "Delhi": 9.1,
      "Pune": 9.2,
      "Chennai": 8.9,
      "Jaipur": 8.6
    }
  },
  {
    "id": "food-2",
    "name": "Specialty Artisanal Coffee Roastery",
    "category": "food",
    "emoji": "\u2615",
    "startupCost": 680000,
    "monthlyRevenue": 340000,
    "roiMonths": 12,
    "competition": "Medium",
    "competitionScore": 8.6,
    "description": "Single-origin pour-overs, cold brews, and sourdough morning brunch in an aesthetic cozy indoor setting.",
    "bestSuitedFor": "Design-minded cafe proprietors targeting remote knowledge workers and coffee purists.",
    "minAreaSqft": 450,
    "targetMarginPercent": 62,
    "recommendedCities": [
      "Jaipur",
      "Bengaluru",
      "Mumbai",
      "Pune",
      "Delhi",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.8,
      "Bengaluru": 9.7,
      "Mumbai": 9.3,
      "Pune": 9.4,
      "Delhi": 9.1,
      "Chennai": 8.9
    }
  },
  {
    "id": "food-3",
    "name": "Artisanal European Sourdough Bakery",
    "category": "food",
    "emoji": "\ud83e\udd50",
    "startupCost": 580000,
    "monthlyRevenue": 260000,
    "roiMonths": 11,
    "competition": "Low",
    "competitionScore": 9.1,
    "description": "Naturally leavened sourdough loaves, French butter croissants, and organic focaccias baked fresh daily.",
    "bestSuitedFor": "Trained pastry chefs targeting premium residential families and gourmet consumers.",
    "minAreaSqft": 350,
    "targetMarginPercent": 65,
    "recommendedCities": [
      "Bengaluru",
      "Mumbai",
      "Delhi",
      "Pune",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.6,
      "Mumbai": 9.5,
      "Delhi": 9.2,
      "Pune": 9.1,
      "Jaipur": 8.9,
      "Chennai": 8.7
    }
  },
  {
    "id": "food-4",
    "name": "Tea Post / Chai Tapri Lounge",
    "category": "food",
    "emoji": "\ud83e\uded6",
    "startupCost": 350000,
    "monthlyRevenue": 180000,
    "roiMonths": 8,
    "competition": "Medium",
    "competitionScore": 8.8,
    "description": "Desi kulhad chai, ginger-cardamom tea varieties, bun maska and quick tea snacks with heavy daily footfalls.",
    "bestSuitedFor": "High-volume retail operators positioned near office towers or university corridors.",
    "minAreaSqft": 200,
    "targetMarginPercent": 50,
    "isFranchise": true,
    "franchiseBrand": "Tea Post",
    "applyUrl": "https://www.teapost.in/franchise",
    "isOfficial": true,
    "recommendedCities": [
      "Jaipur",
      "Pune",
      "Delhi",
      "Bengaluru",
      "Chennai",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.9,
      "Pune": 9.5,
      "Delhi": 9.3,
      "Bengaluru": 9.0,
      "Chennai": 8.8,
      "Mumbai": 8.9
    }
  },
  {
    "id": "food-5",
    "name": "Quick Dumpling & Dimsum Station",
    "category": "food",
    "emoji": "\ud83e\udd5f",
    "startupCost": 320000,
    "monthlyRevenue": 175000,
    "roiMonths": 7,
    "competition": "Medium",
    "competitionScore": 8.4,
    "description": "Steamed and crispy pan-fried gourmet momos, bao buns and spicy garlic dips served in compact kiosk formats.",
    "bestSuitedFor": "Fast-food entrepreneurs capitalizing on youth snacking and evening pedestrian surges.",
    "minAreaSqft": 150,
    "targetMarginPercent": 56,
    "isFranchise": true,
    "franchiseBrand": "Wow Momo",
    "applyUrl": "https://www.wowmomo.com",
    "isOfficial": true,
    "recommendedCities": [
      "Delhi",
      "Bengaluru",
      "Pune",
      "Mumbai",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Delhi": 9.7,
      "Bengaluru": 9.5,
      "Pune": 9.4,
      "Mumbai": 9.2,
      "Jaipur": 9.1,
      "Chennai": 8.6
    }
  },
  {
    "id": "food-6",
    "name": "Healthy Millet Bowls & Superfood Kiosk",
    "category": "food",
    "emoji": "\ud83e\udd57",
    "startupCost": 280000,
    "monthlyRevenue": 145000,
    "roiMonths": 9,
    "competition": "Low",
    "competitionScore": 9.2,
    "description": "Ragi, jowar and quinoa warm grain bowls, protein salads and healthy detox dressings for corporate lunches.",
    "bestSuitedFor": "Nutrition-focused founders targeting IT tech parks and hospital corridor professionals.",
    "minAreaSqft": 180,
    "targetMarginPercent": 54,
    "recommendedCities": [
      "Bengaluru",
      "Chennai",
      "Pune",
      "Mumbai",
      "Delhi",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.8,
      "Chennai": 9.4,
      "Pune": 9.3,
      "Mumbai": 9.1,
      "Delhi": 8.9,
      "Jaipur": 8.5
    }
  },
  {
    "id": "food-7",
    "name": "Belgian Waffle & Dessert Station",
    "category": "food",
    "emoji": "\ud83e\uddc7",
    "startupCost": 340000,
    "monthlyRevenue": 170000,
    "roiMonths": 8,
    "competition": "Medium",
    "competitionScore": 8.3,
    "description": "Crispy pocket waffles layered with melted Belgian chocolate, biscoff spread and soft-serve ice cream.",
    "bestSuitedFor": "High-footfall mall and market entrepreneurs courting evening dessert lovers.",
    "minAreaSqft": 120,
    "targetMarginPercent": 60,
    "recommendedCities": [
      "Mumbai",
      "Bengaluru",
      "Delhi",
      "Jaipur",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Mumbai": 9.6,
      "Bengaluru": 9.4,
      "Delhi": 9.3,
      "Jaipur": 9.2,
      "Pune": 9.1,
      "Chennai": 8.8
    }
  },
  {
    "id": "food-8",
    "name": "Cloud Kitchen for Late-Night Biryani",
    "category": "food",
    "emoji": "\ud83c\udf72",
    "startupCost": 440000,
    "monthlyRevenue": 240000,
    "roiMonths": 8,
    "competition": "High",
    "competitionScore": 7.6,
    "description": "Delivery-only cloud kitchen catering authentic dum biryani, kebabs and gravies until 3:00 AM.",
    "bestSuitedFor": "Culinary teams leveraging Swiggy/Zomato logistics with low ground-floor commercial rent.",
    "minAreaSqft": 300,
    "targetMarginPercent": 46,
    "recommendedCities": [
      "Hyderabad",
      "Bengaluru",
      "Delhi",
      "Pune",
      "Mumbai",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.5,
      "Delhi": 9.4,
      "Pune": 9.3,
      "Mumbai": 9.2,
      "Jaipur": 8.7,
      "Chennai": 8.8
    }
  },
  {
    "id": "food-9",
    "name": "Artisanal Gelato & Sorbets Micro-Parlor",
    "category": "food",
    "emoji": "\ud83c\udf68",
    "startupCost": 520000,
    "monthlyRevenue": 230000,
    "roiMonths": 11,
    "competition": "Low",
    "competitionScore": 8.9,
    "description": "Traditional Italian small-batch gelato with pure whole milk and fresh fruit water sorbets without preservatives.",
    "bestSuitedFor": "Confectioners located in high-income family neighborhoods and promenade streets.",
    "minAreaSqft": 200,
    "targetMarginPercent": 64,
    "recommendedCities": [
      "Mumbai",
      "Bengaluru",
      "Delhi",
      "Jaipur",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Mumbai": 9.7,
      "Bengaluru": 9.4,
      "Delhi": 9.3,
      "Jaipur": 9.1,
      "Pune": 9.0,
      "Chennai": 8.7
    }
  },
  {
    "id": "food-10",
    "name": "Wood-Fired Neapolitan Pizza Bar",
    "category": "food",
    "emoji": "\ud83c\udf55",
    "startupCost": 750000,
    "monthlyRevenue": 360000,
    "roiMonths": 13,
    "competition": "Medium",
    "competitionScore": 8.5,
    "description": "Authentic stone wood-oven pizzas with San Marzano tomato base, fresh buffalo mozzarella and sourdough crust.",
    "bestSuitedFor": "Restaurateurs seeking premium ticket sizes and high dine-in evening beverage attachment.",
    "minAreaSqft": 550,
    "targetMarginPercent": 58,
    "recommendedCities": [
      "Bengaluru",
      "Delhi",
      "Mumbai",
      "Pune",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.6,
      "Delhi": 9.5,
      "Mumbai": 9.4,
      "Pune": 9.2,
      "Jaipur": 9.0,
      "Chennai": 8.8
    }
  },
  {
    "id": "food-11",
    "name": "South Indian Filter Coffee & Tiffin Point",
    "category": "food",
    "emoji": "\ud83e\udd5e",
    "startupCost": 160000,
    "monthlyRevenue": 98000,
    "roiMonths": 6,
    "competition": "Medium",
    "competitionScore": 8.7,
    "description": "Standing counter serving hot degree filter coffee, ghee podi idlis and crispy medu vadas from 6:30 AM.",
    "bestSuitedFor": "Morning rush-hour transit spots and early corporate commuter corridors.",
    "minAreaSqft": 100,
    "targetMarginPercent": 52,
    "recommendedCities": [
      "Chennai",
      "Bengaluru",
      "Pune",
      "Mumbai",
      "Delhi",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Chennai": 9.9,
      "Bengaluru": 9.8,
      "Pune": 9.0,
      "Mumbai": 8.9,
      "Delhi": 8.5,
      "Jaipur": 8.2
    }
  },
  {
    "id": "food-12",
    "name": "Gourmet Kathi Roll & Kebab Counter",
    "category": "food",
    "emoji": "\ud83c\udf2f",
    "startupCost": 240000,
    "monthlyRevenue": 135000,
    "roiMonths": 7,
    "competition": "Medium",
    "competitionScore": 8.2,
    "description": "Flaky egg parathas wrapped around chargrilled paneer tikka and juicy chicken seekh with spicy mint chutney.",
    "bestSuitedFor": "High-density evening pedestrian market corridors and college campus peripheries.",
    "minAreaSqft": 120,
    "targetMarginPercent": 50,
    "recommendedCities": [
      "Delhi",
      "Kolkata",
      "Bengaluru",
      "Pune",
      "Jaipur",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Delhi": 9.7,
      "Pune": 9.3,
      "Bengaluru": 9.1,
      "Jaipur": 9.2,
      "Mumbai": 9.0,
      "Chennai": 8.5
    }
  },
  {
    "id": "food-13",
    "name": "Baskin Robbins Scooping Kiosk",
    "category": "food",
    "emoji": "\ud83c\udf68",
    "startupCost": 600000,
    "monthlyRevenue": 250000,
    "roiMonths": 12,
    "competition": "Low",
    "competitionScore": 8.7,
    "description": "Globally recognized 31 flavors ice cream franchise kiosk with pre-packaged tubs, sundaes and thick shakes.",
    "bestSuitedFor": "Turnkey franchise investors in high-traffic shopping centers and multiplex plazas.",
    "minAreaSqft": 200,
    "targetMarginPercent": 48,
    "isFranchise": true,
    "franchiseBrand": "Baskin Robbins",
    "applyUrl": "https://baskinrobbinsindia.com/franchise-enquiry/",
    "isOfficial": true,
    "recommendedCities": [
      "Bengaluru",
      "Mumbai",
      "Delhi",
      "Jaipur",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.4,
      "Mumbai": 9.5,
      "Delhi": 9.3,
      "Jaipur": 9.2,
      "Pune": 9.1,
      "Chennai": 9.0
    }
  },
  {
    "id": "food-14",
    "name": "Artisanal Kombucha & Fermented Drinks Stand",
    "category": "food",
    "emoji": "\ud83c\udf7e",
    "startupCost": 190000,
    "monthlyRevenue": 105000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 9.3,
    "description": "Naturally effervescent probiotic kombuchas on tap, kefir smoothies and sparkling ginger sodas.",
    "bestSuitedFor": "Wellness innovators catering to young health-conscious lifestyle consumers.",
    "minAreaSqft": 100,
    "targetMarginPercent": 66,
    "recommendedCities": [
      "Bengaluru",
      "Mumbai",
      "Pune",
      "Delhi",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.7,
      "Mumbai": 9.5,
      "Pune": 9.2,
      "Delhi": 9.0,
      "Jaipur": 8.6,
      "Chennai": 8.8
    }
  },
  {
    "id": "fit-1",
    "name": "Boutique Strength & Pilates Studio",
    "category": "fitness",
    "emoji": "\ud83c\udfcb\ufe0f",
    "startupCost": 1400000,
    "monthlyRevenue": 480000,
    "roiMonths": 15,
    "competition": "Low",
    "competitionScore": 9.0,
    "description": "High-end reformer pilates, posture rehabilitation and personal strength coaching with recurring memberships.",
    "bestSuitedFor": "Certified master trainers expanding into their flagship boutique sanctuary.",
    "minAreaSqft": 1200,
    "targetMarginPercent": 68,
    "recommendedCities": [
      "Mumbai",
      "Bengaluru",
      "Delhi",
      "Pune",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Mumbai": 9.8,
      "Bengaluru": 9.6,
      "Delhi": 9.5,
      "Pune": 9.2,
      "Jaipur": 9.1,
      "Chennai": 8.9
    }
  },
  {
    "id": "fit-2",
    "name": "Functional CrossFit & Calisthenics Box",
    "category": "fitness",
    "emoji": "\ud83d\udcaa",
    "startupCost": 850000,
    "monthlyRevenue": 320000,
    "roiMonths": 12,
    "competition": "Low",
    "competitionScore": 8.8,
    "description": "Open turf, Olympic lifting platforms, kettlebells, and high-energy community conditioning workouts.",
    "bestSuitedFor": "Athletes and CrossFit coaches cultivating an enthusiastic fitness tribe.",
    "minAreaSqft": 1000,
    "targetMarginPercent": 60,
    "recommendedCities": [
      "Bengaluru",
      "Pune",
      "Delhi",
      "Mumbai",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.7,
      "Pune": 9.5,
      "Delhi": 9.3,
      "Mumbai": 9.2,
      "Jaipur": 8.9,
      "Chennai": 9.0
    }
  },
  {
    "id": "fit-3",
    "name": "Traditional Hatha Yoga & Meditation Shala",
    "category": "fitness",
    "emoji": "\ud83e\uddd8",
    "startupCost": 280000,
    "monthlyRevenue": 140000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 9.2,
    "description": "Serene bamboo-floored hall for dawn pranayama, evening restorative sound-healing and weekend workshops.",
    "bestSuitedFor": "Spiritual yoga practitioners offering stress relief for corporate professionals.",
    "minAreaSqft": 600,
    "targetMarginPercent": 75,
    "recommendedCities": [
      "Jaipur",
      "Bengaluru",
      "Pune",
      "Chennai",
      "Delhi",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.9,
      "Bengaluru": 9.4,
      "Pune": 9.3,
      "Chennai": 9.2,
      "Delhi": 8.8,
      "Mumbai": 9.0
    }
  },
  {
    "id": "fit-4",
    "name": "Express Men's Grooming Lounge & Beard Bar",
    "category": "fitness",
    "emoji": "\u2702\ufe0f",
    "startupCost": 350000,
    "monthlyRevenue": 180000,
    "roiMonths": 9,
    "competition": "Medium",
    "competitionScore": 8.4,
    "description": "Precision fades, hot-towel shaves, scalp massages and charcoal detox facials in a retro leather ambiance.",
    "bestSuitedFor": "Professional barbers and stylists providing consistent repeat grooming experiences.",
    "minAreaSqft": 300,
    "targetMarginPercent": 55,
    "recommendedCities": [
      "Delhi",
      "Bengaluru",
      "Jaipur",
      "Mumbai",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Delhi": 9.5,
      "Jaipur": 9.6,
      "Bengaluru": 9.3,
      "Mumbai": 9.2,
      "Pune": 9.1,
      "Chennai": 8.8
    }
  },
  {
    "id": "fit-5",
    "name": "Sports Physiotherapy & Spine Rehab Clinic",
    "category": "fitness",
    "emoji": "\ud83e\ude7a",
    "startupCost": 480000,
    "monthlyRevenue": 210000,
    "roiMonths": 11,
    "competition": "Low",
    "competitionScore": 9.3,
    "description": "Dry needling, electrotherapy, postural ergonomic assessments and sports injury rehabilitation sessions.",
    "bestSuitedFor": "Qualified physiotherapists and chiropractors seeking high referral retention.",
    "minAreaSqft": 400,
    "targetMarginPercent": 65,
    "recommendedCities": [
      "Bengaluru",
      "Pune",
      "Delhi",
      "Chennai",
      "Mumbai",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.7,
      "Pune": 9.4,
      "Delhi": 9.3,
      "Chennai": 9.2,
      "Mumbai": 9.1,
      "Jaipur": 8.9
    }
  },
  {
    "id": "fit-6",
    "name": "Jawed Habib Hair & Beauty Franchise",
    "category": "fitness",
    "emoji": "\ud83d\udc87",
    "startupCost": 1200000,
    "monthlyRevenue": 420000,
    "roiMonths": 14,
    "competition": "Medium",
    "competitionScore": 8.6,
    "description": "Household salon franchise with established brand trust, standardized training and high client walk-ins.",
    "bestSuitedFor": "Investors seeking an established turnkey salon franchise with national recognition.",
    "minAreaSqft": 650,
    "targetMarginPercent": 50,
    "isFranchise": true,
    "franchiseBrand": "Jawed Habib",
    "applyUrl": "https://www.jawedhabib.com",
    "isOfficial": true,
    "recommendedCities": [
      "Jaipur",
      "Delhi",
      "Bengaluru",
      "Pune",
      "Mumbai",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.7,
      "Delhi": 9.4,
      "Pune": 9.3,
      "Bengaluru": 9.1,
      "Mumbai": 9.0,
      "Chennai": 8.8
    }
  },
  {
    "id": "fit-7",
    "name": "Kickboxing & Self-Defense Training Club",
    "category": "fitness",
    "emoji": "\ud83e\udd4a",
    "startupCost": 420000,
    "monthlyRevenue": 190000,
    "roiMonths": 9,
    "competition": "Low",
    "competitionScore": 8.9,
    "description": "Muay Thai pads, heavy bag circuit conditioning, and practical women self-defense evening batches.",
    "bestSuitedFor": "Martial artists offering empowering, high-calorie-burn group fitness.",
    "minAreaSqft": 600,
    "targetMarginPercent": 62,
    "recommendedCities": [
      "Delhi",
      "Bengaluru",
      "Pune",
      "Mumbai",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Delhi": 9.6,
      "Bengaluru": 9.4,
      "Pune": 9.3,
      "Mumbai": 9.2,
      "Jaipur": 8.8,
      "Chennai": 8.7
    }
  },
  {
    "id": "fit-8",
    "name": "Cryotherapy & Contrast Therapy Wellness Spa",
    "category": "fitness",
    "emoji": "\u2744\ufe0f",
    "startupCost": 1600000,
    "monthlyRevenue": 520000,
    "roiMonths": 16,
    "competition": "Low",
    "competitionScore": 9.5,
    "description": "Sub-zero whole body cryo chamber, Finnish dry sauna and ice bath tubs for elite athletic recovery.",
    "bestSuitedFor": "Capital-rich wellness entrepreneurs bringing European biohacking luxury to Indian metros.",
    "minAreaSqft": 800,
    "targetMarginPercent": 70,
    "recommendedCities": [
      "Mumbai",
      "Bengaluru",
      "Delhi",
      "Pune",
      "Chennai",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Mumbai": 9.9,
      "Bengaluru": 9.7,
      "Delhi": 9.6,
      "Pune": 9.0,
      "Chennai": 8.9,
      "Jaipur": 8.7
    }
  },
  {
    "id": "fit-9",
    "name": "Dietician Clinic & Healthy Meal Prep Subscriptions",
    "category": "fitness",
    "emoji": "\ud83e\udd57",
    "startupCost": 210000,
    "monthlyRevenue": 115000,
    "roiMonths": 7,
    "competition": "Low",
    "competitionScore": 9.1,
    "description": "Personalized bloodwork-based diet counseling coupled with chef-crafted daily healthy meal tiffin deliveries.",
    "bestSuitedFor": "Nutritionists collaborating with kitchens to monetize custom health regimens.",
    "minAreaSqft": 200,
    "targetMarginPercent": 55,
    "recommendedCities": [
      "Bengaluru",
      "Mumbai",
      "Delhi",
      "Pune",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.7,
      "Mumbai": 9.5,
      "Delhi": 9.3,
      "Pune": 9.2,
      "Jaipur": 8.8,
      "Chennai": 8.9
    }
  },
  {
    "id": "fit-10",
    "name": "Nail Art, Lash Extensions & Brow Studio",
    "category": "fitness",
    "emoji": "\ud83d\udc85",
    "startupCost": 320000,
    "monthlyRevenue": 165000,
    "roiMonths": 8,
    "competition": "Medium",
    "competitionScore": 8.5,
    "description": "Gel nail extensions, chrome finishes, lash lifting and microblading in an ultra-chic Instagrammable parlor.",
    "bestSuitedFor": "Beauty specialists catering to college students, brides, and trendsetters.",
    "minAreaSqft": 250,
    "targetMarginPercent": 65,
    "recommendedCities": [
      "Jaipur",
      "Delhi",
      "Mumbai",
      "Bengaluru",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.6,
      "Delhi": 9.5,
      "Mumbai": 9.4,
      "Bengaluru": 9.2,
      "Pune": 9.1,
      "Chennai": 8.8
    }
  },
  {
    "id": "ret-1",
    "name": "Curated Streetwear & Hype Sneaker Vault",
    "category": "retail",
    "emoji": "\ud83d\udc5f",
    "startupCost": 850000,
    "monthlyRevenue": 380000,
    "roiMonths": 11,
    "competition": "Low",
    "competitionScore": 9.2,
    "description": "Authentic limited-edition kicks, oversized graphic tees, and skateboards in an industrial street-culture setting.",
    "bestSuitedFor": "Fashion influencers and sneakerheads with connections in the global drop ecosystem.",
    "minAreaSqft": 350,
    "targetMarginPercent": 40,
    "recommendedCities": [
      "Delhi",
      "Mumbai",
      "Bengaluru",
      "Pune",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Delhi": 9.7,
      "Mumbai": 9.6,
      "Bengaluru": 9.5,
      "Pune": 9.1,
      "Jaipur": 8.8,
      "Chennai": 8.7
    }
  },
  {
    "id": "ret-2",
    "name": "Lenskart Optical Micro-Store",
    "category": "retail",
    "emoji": "\ud83d\udc53",
    "startupCost": 1500000,
    "monthlyRevenue": 550000,
    "roiMonths": 14,
    "competition": "Low",
    "competitionScore": 9.4,
    "description": "Official omni-channel eyewear franchise with computerized 3D eye exams and best-selling frames.",
    "bestSuitedFor": "Retail investors desiring proven inventory buybacks and high brand advertising support.",
    "minAreaSqft": 400,
    "targetMarginPercent": 35,
    "isFranchise": true,
    "franchiseBrand": "Lenskart",
    "applyUrl": "https://www.lenskart.com/franchise",
    "isOfficial": true,
    "recommendedCities": [
      "Jaipur",
      "Bengaluru",
      "Delhi",
      "Pune",
      "Chennai",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.8,
      "Delhi": 9.6,
      "Bengaluru": 9.5,
      "Pune": 9.4,
      "Chennai": 9.3,
      "Mumbai": 9.2
    }
  },
  {
    "id": "ret-3",
    "name": "Zero-Waste Organic Grocery & Bulk Pantry",
    "category": "retail",
    "emoji": "\ud83d\uded2",
    "startupCost": 420000,
    "monthlyRevenue": 210000,
    "roiMonths": 9,
    "competition": "Low",
    "competitionScore": 8.8,
    "description": "Package-free organic grains, cold-pressed oils on tap, chemical-free home cleaners and cloth tote bags.",
    "bestSuitedFor": "Sustainability advocates targeting upscale eco-conscious gated communities.",
    "minAreaSqft": 350,
    "targetMarginPercent": 36,
    "recommendedCities": [
      "Bengaluru",
      "Pune",
      "Mumbai",
      "Chennai",
      "Delhi",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.7,
      "Pune": 9.4,
      "Mumbai": 9.3,
      "Chennai": 9.1,
      "Delhi": 8.9,
      "Jaipur": 8.6
    }
  },
  {
    "id": "ret-4",
    "name": "Pet Care Boutique & Gourmet Barkery",
    "category": "retail",
    "emoji": "\ud83d\udc3e",
    "startupCost": 350000,
    "monthlyRevenue": 175000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 9.1,
    "description": "Organic dog biscuits, hypoallergenic cat food, stylish harnesses, pet toys and self-service wash stations.",
    "bestSuitedFor": "Passionate pet parents serving the rapidly surging urban companion pet demographic.",
    "minAreaSqft": 250,
    "targetMarginPercent": 48,
    "recommendedCities": [
      "Bengaluru",
      "Mumbai",
      "Pune",
      "Delhi",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.8,
      "Mumbai": 9.6,
      "Pune": 9.4,
      "Delhi": 9.3,
      "Jaipur": 8.9,
      "Chennai": 8.8
    }
  },
  {
    "id": "ret-5",
    "name": "Artisanal Studio Pottery & Home Linen",
    "category": "retail",
    "emoji": "\ud83c\udffa",
    "startupCost": 320000,
    "monthlyRevenue": 160000,
    "roiMonths": 9,
    "competition": "Low",
    "competitionScore": 9.0,
    "description": "Handcrafted ceramic dinner sets, hand-thrown clay mugs, handblock-printed cotton bedsheets and curtains.",
    "bestSuitedFor": "Artisans and curators showcasing authentic regional craftsmanship with modern sensibilities.",
    "minAreaSqft": 300,
    "targetMarginPercent": 54,
    "recommendedCities": [
      "Jaipur",
      "Bengaluru",
      "Delhi",
      "Mumbai",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.9,
      "Delhi": 9.4,
      "Bengaluru": 9.3,
      "Mumbai": 9.2,
      "Pune": 9.0,
      "Chennai": 8.7
    }
  },
  {
    "id": "ret-6",
    "name": "Kids Montessori Educational Toy Store",
    "category": "retail",
    "emoji": "\ud83e\uddf8",
    "startupCost": 290000,
    "monthlyRevenue": 140000,
    "roiMonths": 9,
    "competition": "Low",
    "competitionScore": 8.9,
    "description": "Non-toxic wooden blocks, STEM experiment kits, sensory puzzles and illustrated multilingual storybooks.",
    "bestSuitedFor": "Educators looking to offer screen-free developmental play for mindful young families.",
    "minAreaSqft": 250,
    "targetMarginPercent": 45,
    "recommendedCities": [
      "Bengaluru",
      "Pune",
      "Chennai",
      "Delhi",
      "Jaipur",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.7,
      "Pune": 9.4,
      "Chennai": 9.2,
      "Delhi": 9.1,
      "Jaipur": 8.8,
      "Mumbai": 9.0
    }
  },
  {
    "id": "ret-7",
    "name": "Premium Dry Fruits & Gourmet Gifting Mart",
    "category": "retail",
    "emoji": "\ud83e\udd5c",
    "startupCost": 480000,
    "monthlyRevenue": 240000,
    "roiMonths": 10,
    "competition": "Medium",
    "competitionScore": 8.4,
    "description": "Californian almonds, Afghani anjeer, roasted peri-peri cashews, exotic berries and bespoke festive corporate hampers.",
    "bestSuitedFor": "Merchants capitalizing on wedding seasons, Diwali corporate gifting and wellness snacking.",
    "minAreaSqft": 250,
    "targetMarginPercent": 38,
    "recommendedCities": [
      "Delhi",
      "Jaipur",
      "Mumbai",
      "Bengaluru",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Delhi": 9.7,
      "Jaipur": 9.8,
      "Mumbai": 9.4,
      "Bengaluru": 9.2,
      "Pune": 9.1,
      "Chennai": 8.9
    }
  },
  {
    "id": "ret-8",
    "name": "Boutique Perfumery & Custom Attar Bar",
    "category": "retail",
    "emoji": "\ud83c\udf38",
    "startupCost": 260000,
    "monthlyRevenue": 145000,
    "roiMonths": 7,
    "competition": "Low",
    "competitionScore": 9.2,
    "description": "Alcohol-free pure attars, French perfume oils, oud blends, and custom personalized signature fragrance creation.",
    "bestSuitedFor": "Fragrance enthusiasts offering affordable luxury alternatives to expensive imported perfumes.",
    "minAreaSqft": 150,
    "targetMarginPercent": 68,
    "recommendedCities": [
      "Jaipur",
      "Delhi",
      "Mumbai",
      "Hyderabad",
      "Bengaluru",
      "Pune"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.8,
      "Delhi": 9.5,
      "Mumbai": 9.4,
      "Bengaluru": 9.1,
      "Pune": 8.9,
      "Chennai": 8.7
    }
  },
  {
    "id": "ret-9",
    "name": "Smart Luggage & Nomad Travel Gear",
    "category": "retail",
    "emoji": "\ud83e\uddf3",
    "startupCost": 390000,
    "monthlyRevenue": 180000,
    "roiMonths": 10,
    "competition": "Low",
    "competitionScore": 8.7,
    "description": "Polycarbonate carry-ons, anti-theft tech backpacks, packing cubes, travel neck pillows and universal power adapters.",
    "bestSuitedFor": "Retailers positioned near tech clusters, transit hubs, and airports serving frequent travelers.",
    "minAreaSqft": 250,
    "targetMarginPercent": 42,
    "recommendedCities": [
      "Bengaluru",
      "Mumbai",
      "Delhi",
      "Pune",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.6,
      "Mumbai": 9.5,
      "Delhi": 9.3,
      "Pune": 9.1,
      "Jaipur": 8.8,
      "Chennai": 8.9
    }
  },
  {
    "id": "ret-10",
    "name": "Handloom Sarees & Contemporary Ethnic Studio",
    "category": "retail",
    "emoji": "\ud83d\udc58",
    "startupCost": 620000,
    "monthlyRevenue": 290000,
    "roiMonths": 11,
    "competition": "Medium",
    "competitionScore": 8.5,
    "description": "Chanderi, Kota Doria, and Banarasi handwoven sarees paired with custom designer blouse stitching services.",
    "bestSuitedFor": "Fashion designers with direct weaver artisan relationships in regional craft clusters.",
    "minAreaSqft": 400,
    "targetMarginPercent": 45,
    "recommendedCities": [
      "Jaipur",
      "Chennai",
      "Delhi",
      "Bengaluru",
      "Pune",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.9,
      "Chennai": 9.5,
      "Delhi": 9.3,
      "Bengaluru": 9.2,
      "Pune": 9.0,
      "Mumbai": 9.1
    }
  },
  {
    "id": "ret-11",
    "name": "Specialty Fine Art Supplies & Stationery",
    "category": "retail",
    "emoji": "\ud83c\udfa8",
    "startupCost": 280000,
    "monthlyRevenue": 135000,
    "roiMonths": 9,
    "competition": "Low",
    "competitionScore": 8.8,
    "description": "Artist-grade acrylics, cotton watercolor papers, architecture drafting tools, and fountain pen inks.",
    "bestSuitedFor": "Fine art lovers stationed near architecture, design, or fine arts colleges.",
    "minAreaSqft": 200,
    "targetMarginPercent": 40,
    "recommendedCities": [
      "Pune",
      "Bengaluru",
      "Mumbai",
      "Delhi",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Pune": 9.6,
      "Bengaluru": 9.5,
      "Mumbai": 9.3,
      "Delhi": 9.2,
      "Jaipur": 8.9,
      "Chennai": 8.8
    }
  },
  {
    "id": "ret-12",
    "name": "Indoor Greenery, Succulents & Planter Studio",
    "category": "retail",
    "emoji": "\ud83e\udeb4",
    "startupCost": 220000,
    "monthlyRevenue": 110000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 9.1,
    "description": "Air-purifying snake plants, monsteras, ceramic pots, coco-peat mixes and corporate desk-plant rental packages.",
    "bestSuitedFor": "Botanical stylists catering to apartment dwellers and green corporate workspaces.",
    "minAreaSqft": 200,
    "targetMarginPercent": 60,
    "recommendedCities": [
      "Bengaluru",
      "Pune",
      "Mumbai",
      "Delhi",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.8,
      "Pune": 9.4,
      "Mumbai": 9.3,
      "Delhi": 9.1,
      "Jaipur": 8.8,
      "Chennai": 8.7
    }
  },
  {
    "id": "edu-1",
    "name": "STEM, Robotics & Coding Lab for Young Minds",
    "category": "education",
    "emoji": "\ud83e\udd16",
    "startupCost": 320000,
    "monthlyRevenue": 170000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 9.3,
    "description": "Lego robotics, scratch visual coding, 3D pen modeling and hands-on scientific experiment batches for kids 6-16.",
    "bestSuitedFor": "Engineers and educators in densely populated family suburbs with high parental ambition.",
    "minAreaSqft": 450,
    "targetMarginPercent": 70,
    "recommendedCities": [
      "Bengaluru",
      "Pune",
      "Delhi",
      "Chennai",
      "Jaipur",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.9,
      "Pune": 9.6,
      "Delhi": 9.3,
      "Chennai": 9.4,
      "Jaipur": 9.0,
      "Mumbai": 9.2
    }
  },
  {
    "id": "edu-2",
    "name": "IELTS, TOEFL & Global Education Academy",
    "category": "education",
    "emoji": "\ud83c\udf93",
    "startupCost": 270000,
    "monthlyRevenue": 155000,
    "roiMonths": 7,
    "competition": "Medium",
    "competitionScore": 8.6,
    "description": "Intensive language test prep, mock speaking labs, visa interview guidance and overseas university applications.",
    "bestSuitedFor": "Language coaches and overseas study advisors serving college students and visa applicants.",
    "minAreaSqft": 350,
    "targetMarginPercent": 72,
    "recommendedCities": [
      "Pune",
      "Jaipur",
      "Delhi",
      "Bengaluru",
      "Chennai",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.7,
      "Pune": 9.6,
      "Delhi": 9.4,
      "Bengaluru": 9.1,
      "Chennai": 9.0,
      "Mumbai": 8.9
    }
  },
  {
    "id": "edu-3",
    "name": "Digital Marketing & AI Tools Career Accelerator",
    "category": "education",
    "emoji": "\ud83d\udcca",
    "startupCost": 290000,
    "monthlyRevenue": 160000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 9.0,
    "description": "Cohort-based weekend bootcamp teaching SEO, performance ads, Generative AI workflows, and freelance portfolio prep.",
    "bestSuitedFor": "Experienced marketing managers upskilling college graduates and small business owners.",
    "minAreaSqft": 350,
    "targetMarginPercent": 75,
    "recommendedCities": [
      "Bengaluru",
      "Delhi",
      "Pune",
      "Mumbai",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.8,
      "Delhi": 9.5,
      "Pune": 9.4,
      "Mumbai": 9.3,
      "Jaipur": 9.1,
      "Chennai": 8.9
    }
  },
  {
    "id": "edu-4",
    "name": "Acoustic Music, Guitar & Keyboard Academy",
    "category": "education",
    "emoji": "\ud83c\udfb8",
    "startupCost": 240000,
    "monthlyRevenue": 125000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 8.9,
    "description": "Sound-dampened studio rooms for Trinity College grade exam training in guitar, piano, drums and Hindustani vocals.",
    "bestSuitedFor": "Passionate musicians nurturing creative artistic talents in residential pockets.",
    "minAreaSqft": 350,
    "targetMarginPercent": 70,
    "recommendedCities": [
      "Bengaluru",
      "Pune",
      "Chennai",
      "Mumbai",
      "Delhi",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.7,
      "Pune": 9.5,
      "Chennai": 9.3,
      "Mumbai": 9.2,
      "Delhi": 9.0,
      "Jaipur": 8.7
    }
  },
  {
    "id": "edu-5",
    "name": "Quiet Coworking & Competitive Exam Study Den",
    "category": "education",
    "emoji": "\ud83d\udcda",
    "startupCost": 380000,
    "monthlyRevenue": 190000,
    "roiMonths": 9,
    "competition": "Medium",
    "competitionScore": 8.5,
    "description": "24/7 soundproof air-conditioned study pods with ergonomic chairs, high-speed fiber WiFi and free tea for UPSC & CA aspirants.",
    "bestSuitedFor": "Real estate owners converting first-floor or basement spaces into recurring monthly desk subscriptions.",
    "minAreaSqft": 800,
    "targetMarginPercent": 65,
    "recommendedCities": [
      "Jaipur",
      "Delhi",
      "Pune",
      "Bengaluru",
      "Chennai",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.9,
      "Delhi": 9.8,
      "Pune": 9.7,
      "Bengaluru": 9.0,
      "Chennai": 9.1,
      "Mumbai": 8.6
    }
  },
  {
    "id": "edu-6",
    "name": "Speed Math, Abacus & Early Logic Center",
    "category": "education",
    "emoji": "\ud83e\uddee",
    "startupCost": 170000,
    "monthlyRevenue": 95000,
    "roiMonths": 6,
    "competition": "Low",
    "competitionScore": 9.1,
    "description": "Mental arithmetic abacus coaching, Rubik's cube mastery and Vedic math calculation speed techniques for children 5-12.",
    "bestSuitedFor": "Home tutors and math teachers transitioning into a commercial community coaching center.",
    "minAreaSqft": 200,
    "targetMarginPercent": 80,
    "recommendedCities": [
      "Chennai",
      "Bengaluru",
      "Pune",
      "Jaipur",
      "Delhi",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Chennai": 9.8,
      "Bengaluru": 9.6,
      "Pune": 9.4,
      "Jaipur": 9.2,
      "Delhi": 9.0,
      "Mumbai": 8.9
    }
  },
  {
    "id": "edu-7",
    "name": "Professional Barista & Baking Skills Institute",
    "category": "education",
    "emoji": "\u2615",
    "startupCost": 520000,
    "monthlyRevenue": 230000,
    "roiMonths": 11,
    "competition": "Low",
    "competitionScore": 9.4,
    "description": "Hands-on commercial espresso machine calibration, latte art workshops and certified commercial sourdough baking courses.",
    "bestSuitedFor": "Hospitality veterans training staff for the booming cafe and restaurant industry.",
    "minAreaSqft": 450,
    "targetMarginPercent": 68,
    "recommendedCities": [
      "Bengaluru",
      "Jaipur",
      "Mumbai",
      "Delhi",
      "Pune",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Bengaluru": 9.8,
      "Jaipur": 9.6,
      "Mumbai": 9.4,
      "Delhi": 9.2,
      "Pune": 9.1,
      "Chennai": 8.8
    }
  },
  {
    "id": "edu-8",
    "name": "Public Speaking, Debate & Drama Workshop",
    "category": "education",
    "emoji": "\ud83c\udfad",
    "startupCost": 220000,
    "monthlyRevenue": 115000,
    "roiMonths": 7,
    "competition": "Low",
    "competitionScore": 9.0,
    "description": "Model United Nations (MUN) preparation, voice modulation, stage acting and corporate executive presentation training.",
    "bestSuitedFor": "Theatre artists and communications coaches building self-confidence in youth.",
    "minAreaSqft": 300,
    "targetMarginPercent": 75,
    "recommendedCities": [
      "Mumbai",
      "Delhi",
      "Bengaluru",
      "Pune",
      "Jaipur",
      "Chennai"
    ],
    "cityViabilityScores": {
      "Mumbai": 9.7,
      "Delhi": 9.5,
      "Bengaluru": 9.4,
      "Pune": 9.2,
      "Jaipur": 8.9,
      "Chennai": 8.8
    }
  },
  {
    "id": "edu-9",
    "name": "Foreign Language & Cross-Cultural Academy",
    "category": "education",
    "emoji": "\ud83c\udf0d",
    "startupCost": 250000,
    "monthlyRevenue": 135000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 8.9,
    "description": "German, French, Spanish and Japanese conversational certifications for engineers and outbound travelers.",
    "bestSuitedFor": "Linguists capitalizing on global tech relocation and international trade careers.",
    "minAreaSqft": 300,
    "targetMarginPercent": 72,
    "recommendedCities": [
      "Pune",
      "Bengaluru",
      "Delhi",
      "Chennai",
      "Mumbai",
      "Jaipur"
    ],
    "cityViabilityScores": {
      "Pune": 9.8,
      "Bengaluru": 9.7,
      "Delhi": 9.3,
      "Chennai": 9.2,
      "Mumbai": 9.1,
      "Jaipur": 8.8
    }
  },
  {
    "id": "edu-10",
    "name": "Classical Dance, Kathak & Contemporary Studio",
    "category": "education",
    "emoji": "\ud83e\ude70",
    "startupCost": 260000,
    "monthlyRevenue": 130000,
    "roiMonths": 8,
    "competition": "Low",
    "competitionScore": 9.1,
    "description": "Polished teakwood mirrored dance hall hosting graded Kathak, Bharatanatyam and fitness Zumba batches.",
    "bestSuitedFor": "Accomplished dance gurus seeking an inspiring studio space for student recitals.",
    "minAreaSqft": 500,
    "targetMarginPercent": 70,
    "recommendedCities": [
      "Jaipur",
      "Chennai",
      "Delhi",
      "Bengaluru",
      "Pune",
      "Mumbai"
    ],
    "cityViabilityScores": {
      "Jaipur": 9.9,
      "Chennai": 9.8,
      "Delhi": 9.3,
      "Bengaluru": 9.2,
      "Pune": 9.0,
      "Mumbai": 9.1
    }
  }
];

export const MOCK_BUSINESSES = EXTENDED_BUSINESS_OPPORTUNITIES;
export default EXTENDED_BUSINESS_OPPORTUNITIES;


export const businessFinderDb = {
  getAllOpportunities(): BusinessOpportunity[] {
    if (!BUSINESS_FINDER_FLAGS.USE_MOCK_FALLBACK) {
      return [...ACTUAL_LIVE_OPPORTUNITIES];
    }
    // High priority to actual data at top, mock data at bottom
    return [...ACTUAL_LIVE_OPPORTUNITIES, ...EXTENDED_BUSINESS_OPPORTUNITIES];
  },

  setMockFallbackEnabled(enabled: boolean): void {
    BUSINESS_FINDER_FLAGS.USE_MOCK_FALLBACK = enabled;
  }
};
