import type {
  GeoLocation,
  CommercialProperty,
  Franchise,
  BusinessOpportunity,
  CompetitorItem,
  StoreTelemetry,
  MarketKPI,
  UserSession,
} from './m_schema';

export const PRESENTATION_LOCATIONS: GeoLocation[] = [
  {
    id: 'loc-1',
    name: 'Koramangala, Bengaluru',
    shortName: 'Koramangala',
    city: 'Bengaluru',
    state: 'Karnataka',
    lat: 12.9352,
    lng: 77.6245,
    marketTier: 'Tier 1',
    avgRentSqft: 135,
    footfallDensity: 'Very High',
    opportunityScore: 8.9,
  },
  {
    id: 'loc-2',
    name: 'Connaught Place, New Delhi',
    shortName: 'Connaught Place',
    city: 'Delhi',
    state: 'Delhi',
    lat: 28.6315,
    lng: 77.2167,
    marketTier: 'Tier 1',
    avgRentSqft: 195,
    footfallDensity: 'Very High',
    opportunityScore: 9.1,
  },
  {
    id: 'loc-3',
    name: 'Indiranagar 100ft Road, Bengaluru',
    shortName: 'Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    lat: 12.9784,
    lng: 77.6408,
    marketTier: 'Tier 1',
    avgRentSqft: 145,
    footfallDensity: 'High',
    opportunityScore: 8.7,
  },
  {
    id: 'loc-4',
    name: 'Cyber Hub, Gurugram',
    shortName: 'Cyber Hub',
    city: 'Gurugram',
    state: 'Haryana',
    lat: 28.4952,
    lng: 77.0892,
    marketTier: 'Tier 1',
    avgRentSqft: 165,
    footfallDensity: 'Very High',
    opportunityScore: 8.6,
  },
  {
    id: 'loc-5',
    name: 'Malviya Nagar, Jaipur',
    shortName: 'Malviya Nagar',
    city: 'Jaipur',
    state: 'Rajasthan',
    lat: 26.8539,
    lng: 75.8152,
    marketTier: 'Tier 2',
    avgRentSqft: 65,
    footfallDensity: 'High',
    opportunityScore: 8.2,
  },
  {
    id: 'loc-6',
    name: 'Lower Parel, Mumbai',
    shortName: 'Lower Parel',
    city: 'Mumbai',
    state: 'Maharashtra',
    lat: 18.9986,
    lng: 72.8306,
    marketTier: 'Tier 1',
    avgRentSqft: 220,
    footfallDensity: 'Very High',
    opportunityScore: 8.8,
  },
  {
    id: 'loc-7',
    name: 'Hinjewadi Phase 1, Pune',
    shortName: 'Hinjewadi',
    city: 'Pune',
    state: 'Maharashtra',
    lat: 18.5913,
    lng: 73.7389,
    marketTier: 'Tier 2',
    avgRentSqft: 75,
    footfallDensity: 'Medium',
    opportunityScore: 7.9,
  },
  {
    id: 'loc-8',
    name: 'T. Nagar, Chennai',
    shortName: 'T. Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    lat: 13.0418,
    lng: 80.2341,
    marketTier: 'Tier 1',
    avgRentSqft: 110,
    footfallDensity: 'Very High',
    opportunityScore: 8.5,
  },
  {
    id: 'loc-9',
    name: 'Salt Lake Sector V, Kolkata',
    shortName: 'Sector V',
    city: 'Kolkata',
    state: 'West Bengal',
    lat: 22.5804,
    lng: 88.4378,
    marketTier: 'Tier 2',
    avgRentSqft: 60,
    footfallDensity: 'Medium',
    opportunityScore: 7.6,
  },
];

export const PRESENTATION_PROPERTIES: CommercialProperty[] = [
  {
    id: 'prop-1',
    title: 'Prime Retail Corner Space – Connaught Place',
    type: 'Shop',
    city: 'Delhi',
    area: 'Connaught Place Inner Circle',
    sizeSqft: 450,
    rentPerSqft: 150,
    monthlyRent: 67500,
    footfallRating: 9.4,
    nearbyBusinesses: 42,
    highlights: ['Corner Glass Frontage', 'Metro Station 200m', '3-Phase Power', 'High Walk-in Demand'],
    contact: '+91 98100 11001',
    available: true,
    lat: 28.6315,
    lng: 77.2167,
  },
  {
    id: 'prop-2',
    title: 'Modern High Street Boutique – Indiranagar',
    type: 'Shop',
    city: 'Bengaluru',
    area: '100ft Road, Indiranagar',
    sizeSqft: 600,
    rentPerSqft: 125,
    monthlyRent: 75000,
    footfallRating: 9.0,
    nearbyBusinesses: 51,
    highlights: ['Prime Boulevard Footfall', 'Surrounded by Cafes', 'Dedicated Valet Slot'],
    contact: '+91 98100 22002',
    available: true,
    lat: 12.9784,
    lng: 77.6408,
  },
  {
    id: 'prop-3',
    title: 'Corporate Plaza Food Kiosk – Cyber Hub',
    type: 'Kiosk',
    city: 'Gurugram',
    area: 'DLF Cyber Hub Phase 2',
    sizeSqft: 180,
    rentPerSqft: 220,
    monthlyRent: 39600,
    footfallRating: 9.6,
    nearbyBusinesses: 74,
    highlights: ['Centrally Air-conditioned', 'Massive Tech Crowd', 'Kitchen Grease Trap Ready'],
    contact: '+91 98100 33003',
    available: true,
    lat: 28.4952,
    lng: 77.0892,
  },
  {
    id: 'prop-4',
    title: 'Affordable Market Shop – Malviya Nagar',
    type: 'Shop',
    city: 'Jaipur',
    area: 'Sector 3 Market, Malviya Nagar',
    sizeSqft: 320,
    rentPerSqft: 55,
    monthlyRent: 17600,
    footfallRating: 7.8,
    nearbyBusinesses: 26,
    highlights: ['Dense Residential Catchment', 'Ground Floor Access', 'Low Maintenance Overhead'],
    contact: '+91 98100 44004',
    available: true,
    lat: 26.8539,
    lng: 75.8152,
  },
  {
    id: 'prop-5',
    title: 'Executive Studio Office – Lower Parel',
    type: 'Office',
    city: 'Mumbai',
    area: 'Peninsula Business Park',
    sizeSqft: 1400,
    rentPerSqft: 160,
    monthlyRent: 224000,
    footfallRating: 8.8,
    nearbyBusinesses: 60,
    highlights: ['Furnished Grade-A Space', 'Conference Rooms', 'High-Speed Elevators'],
    contact: '+91 98100 55005',
    available: true,
    lat: 18.9986,
    lng: 72.8306,
  },
  {
    id: 'prop-6',
    title: 'Highway Commercial Land Parcel – Hinjewadi',
    type: 'Commercial Land',
    city: 'Pune',
    area: 'Hinjewadi Phase 1 Main Road',
    sizeSqft: 6000,
    rentPerSqft: 0,
    monthlyRent: 0,
    salePrice: 14500000,
    footfallRating: 8.1,
    nearbyBusinesses: 34,
    highlights: ['Direct Highway Frontage', 'Approved for Mixed Commercial', 'Freehold Title'],
    contact: '+91 98100 66006',
    available: true,
    lat: 18.5913,
    lng: 73.7389,
  },
  {
    id: 'prop-7',
    title: 'High Walk-in Retail Space – T. Nagar',
    type: 'Shop',
    city: 'Chennai',
    area: 'Pondy Bazaar, T. Nagar',
    sizeSqft: 500,
    rentPerSqft: 90,
    monthlyRent: 45000,
    footfallRating: 9.3,
    nearbyBusinesses: 68,
    highlights: ['Pedestrian Plaza Adjacent', 'Textile & Gold Market', 'Continuous Daily Footfall'],
    contact: '+91 98100 77007',
    available: true,
    lat: 13.0418,
    lng: 80.2341,
  },
  {
    id: 'prop-8',
    title: 'Tech Park Co-working Floor – Salt Lake',
    type: 'Office',
    city: 'Kolkata',
    area: 'Sector V Ring Road',
    sizeSqft: 2200,
    rentPerSqft: 48,
    monthlyRent: 105600,
    footfallRating: 7.9,
    nearbyBusinesses: 39,
    highlights: ['Fiber Internet Hub', 'Metro Connectivity', 'Cafeteria Onsite'],
    contact: '+91 98100 88008',
    available: true,
    lat: 22.5804,
    lng: 88.4378,
  },
];

export const PRESENTATION_FRANCHISES: Franchise[] = [
  {
    id: 'fran-1',
    brand: 'Wow Momo',
    logoColor: '#FF6B35',
    category: 'Food & Beverage',
    investment: 1200000,
    franchiseFee: 200000,
    royaltyPercent: 6,
    roiMonths: 16,
    outlets: 650,
    description: "India's largest momo QSR brand. High operating margins with central kitchen supply.",
    preferredLocations: ['Malls', 'High Street Markets', 'Tech Parks'],
    minAreaSqft: 200,
  },
  {
    id: 'fran-2',
    brand: 'Chai Sutta Bar',
    logoColor: '#E63946',
    category: 'Beverages & Snacks',
    investment: 850000,
    franchiseFee: 150000,
    royaltyPercent: 5,
    roiMonths: 12,
    outlets: 520,
    description: 'Youth-centric chai cafe chain served in traditional kulhads with viral brand recall.',
    preferredLocations: ['Near Colleges', 'Transit Hubs', 'High Street'],
    minAreaSqft: 150,
  },
  {
    id: 'fran-3',
    brand: 'Lenskart',
    logoColor: '#2563EB',
    category: 'Retail Eyewear',
    investment: 2800000,
    franchiseFee: 400000,
    royaltyPercent: 7,
    roiMonths: 22,
    outlets: 2100,
    description: 'Omnichannel optical giant. Guaranteed zero inventory risk with central lab delivery.',
    preferredLocations: ['Premium Malls', 'Tier 1 & 2 High Streets'],
    minAreaSqft: 350,
  },
  {
    id: 'fran-4',
    brand: 'Jawed Habib',
    logoColor: '#7C3AED',
    category: 'Salon & Grooming',
    investment: 1600000,
    franchiseFee: 250000,
    royaltyPercent: 6,
    roiMonths: 18,
    outlets: 1150,
    description: 'Premier Indian salon & wellness network. Trained staff pool provided by academy.',
    preferredLocations: ['Residential Townships', 'Malls', 'Main Markets'],
    minAreaSqft: 300,
  },
  {
    id: 'fran-5',
    brand: 'DTDC Express',
    logoColor: '#059669',
    category: 'Logistics & Courier',
    investment: 250000,
    franchiseFee: 50000,
    royaltyPercent: 4,
    roiMonths: 8,
    outlets: 12500,
    description: 'Low-capital logistics franchise with steady daily commercial B2B bookings.',
    preferredLocations: ['Commercial Markets', 'Industrial Areas', 'Residential Hubs'],
    minAreaSqft: 100,
  },
  {
    id: 'fran-6',
    brand: 'Naturals Ice Cream',
    logoColor: '#D97706',
    category: 'Food & Beverage',
    investment: 1900000,
    franchiseFee: 300000,
    royaltyPercent: 5,
    roiMonths: 20,
    outlets: 380,
    description: 'Beloved artisan fruit ice cream chain with high brand equity and repeat footfall.',
    preferredLocations: ['Upscale Corridors', 'Malls', 'Dining Precincts'],
    minAreaSqft: 250,
  },
  {
    id: 'fran-7',
    brand: 'FirstCry Stores',
    logoColor: '#EC4899',
    category: 'Baby & Kids Retail',
    investment: 3600000,
    franchiseFee: 500000,
    royaltyPercent: 6,
    roiMonths: 26,
    outlets: 490,
    description: "Asia's largest online-offline kids brand with exceptionally high average order values.",
    preferredLocations: ['Major High Streets', 'Prime Malls'],
    minAreaSqft: 600,
  },
  {
    id: 'fran-8',
    brand: 'Amul Parlour',
    logoColor: '#F59E0B',
    category: 'Dairy & Confectionery',
    investment: 250000,
    franchiseFee: 0,
    royaltyPercent: 0,
    roiMonths: 6,
    outlets: 10500,
    description: 'Zero royalty, zero franchise fee. Massive public trust and fast daily inventory turn.',
    preferredLocations: ['Residential Gates', 'Market Corners', 'Railway Stations'],
    minAreaSqft: 120,
  },
];

export const PRESENTATION_BUSINESS_OPPORTUNITIES: BusinessOpportunity[] = [
  {
    id: 'biz-1',
    name: 'Cloud Kitchen Hub',
    emoji: '🍳',
    startupCost: 320000,
    monthlyRevenue: 195000,
    roiMonths: 14,
    competition: 'Low',
    competitionScore: 8.8,
    description: 'Delivery-only commercial kitchen optimized for Swiggy & Zomato without high street front rent.',
    bestSuitedFor: 'Culinary operators with digital marketing focus.',
  },
  {
    id: 'biz-2',
    name: 'Specialty Artisan Cafe',
    emoji: '☕',
    startupCost: 850000,
    monthlyRevenue: 340000,
    roiMonths: 18,
    competition: 'Medium',
    competitionScore: 7.2,
    description: 'Third-wave coffee and co-working corner catering to founders, students, and hybrid teams.',
    bestSuitedFor: 'Entrepreneurs seeking high dwell time and community repeat visits.',
  },
  {
    id: 'biz-3',
    name: 'Fresh Cold-Pressed Juice Bar',
    emoji: '🥤',
    startupCost: 180000,
    monthlyRevenue: 95000,
    roiMonths: 10,
    competition: 'Medium',
    competitionScore: 7.8,
    description: 'Compact healthy beverage station with minimal refrigeration waste and high morning traffic.',
    bestSuitedFor: 'First-time retail founders looking for quick payback.',
  },
  {
    id: 'biz-4',
    name: 'Express Mobile & Tech Care',
    emoji: '📱',
    startupCost: 150000,
    monthlyRevenue: 85000,
    roiMonths: 8,
    competition: 'Low',
    competitionScore: 8.4,
    description: 'On-demand screen repair and accessories center located near transit corridors.',
    bestSuitedFor: 'Technically inclined operators with customer service orientation.',
  },
  {
    id: 'biz-5',
    name: 'Boutique Strength & Pilates Studio',
    emoji: '🏋️',
    startupCost: 1400000,
    monthlyRevenue: 420000,
    roiMonths: 20,
    competition: 'Low',
    competitionScore: 8.6,
    description: 'Premium subscription-based micro gym with high-ticket memberships and steady cash flow.',
    bestSuitedFor: 'Fitness trainers expanding into their first brick-and-mortar venture.',
  },
  {
    id: 'biz-6',
    name: 'STEM & Coding Academy for Kids',
    emoji: '📚',
    startupCost: 280000,
    monthlyRevenue: 160000,
    roiMonths: 11,
    competition: 'Medium',
    competitionScore: 6.9,
    description: 'Weekend hands-on robotics, math, and coding workshops with high parent retention rates.',
    bestSuitedFor: 'Educators and engineers in densely populated residential family suburbs.',
  },
];

export const PRESENTATION_COMPETITORS: CompetitorItem[] = [
  {
    id: 'comp-1',
    name: 'Blue Tokai Coffee Roasters',
    category: 'Coffee & Cafe',
    area: 'Koramangala 4th Block',
    city: 'Bengaluru',
    priceLevel: 'Mid',
    avgTicket: 320,
    dailyCustomers: 185,
    rating: 4.6,
  },
  {
    id: 'comp-2',
    name: 'Third Wave Coffee',
    category: 'Coffee & Cafe',
    area: '100ft Road, Indiranagar',
    city: 'Bengaluru',
    priceLevel: 'Mid',
    avgTicket: 290,
    dailyCustomers: 210,
    rating: 4.5,
  },
  {
    id: 'comp-3',
    name: 'Starbucks Reserve',
    category: 'Coffee & Cafe',
    area: 'Connaught Place Inner Circle',
    city: 'Delhi',
    priceLevel: 'Premium',
    avgTicket: 450,
    dailyCustomers: 290,
    rating: 4.7,
  },
  {
    id: 'comp-4',
    name: 'Chai Point',
    category: 'Beverage QSR',
    area: 'DLF Cyber Hub',
    city: 'Gurugram',
    priceLevel: 'Budget',
    avgTicket: 110,
    dailyCustomers: 480,
    rating: 4.2,
  },
  {
    id: 'comp-5',
    name: 'Social Offline',
    category: 'Cafe / Bar',
    area: 'Koramangala 5th Block',
    city: 'Bengaluru',
    priceLevel: 'Mid',
    avgTicket: 650,
    dailyCustomers: 340,
    rating: 4.4,
  },
];

export const PRESENTATION_STORE_TELEMETRY: StoreTelemetry = {
  storeId: 'store-vm-001',
  storeName: 'Atrix',
  ownerName: 'Abhinav Choudhary',
  category: 'Cafe',
  city: 'Jaipur',
  locality: 'C-scheme, Jaipur, Raj',
  sizeSqft: 650,
  monthlyRent: 62000,
  monthlyRevenue: 485000,
  dailyFootfall: 520,
  conversionRate: 38.5,
  rentToRevenueRatio: 12.8, // Healthy below 20%
  hourlyTraffic: [
    { hour: '8 AM', weekday: 28, weekend: 34 },
    { hour: '10 AM', weekday: 74, weekend: 85 },
    { hour: '12 PM', weekday: 96, weekend: 110 },
    { hour: '2 PM', weekday: 65, weekend: 78 },
    { hour: '4 PM', weekday: 88, weekend: 115 },
    { hour: '6 PM', weekday: 142, weekend: 180 },
    { hour: '8 PM', weekday: 168, weekend: 210 },
    { hour: '10 PM', weekday: 82, weekend: 105 },
  ],
  nearbyCompetitors: [
    { name: 'Curious Life Coffee Roasters (250m)', distanceMeters: 250, footfallShare: 31 },
    { name: 'Town Coffee C-Scheme (400m)', distanceMeters: 400, footfallShare: 26 },
    { name: 'Roastery Coffee House (650m)', distanceMeters: 650, footfallShare: 24 },
    { name: 'Local Chai Tapri Hub (120m)', distanceMeters: 120, footfallShare: 19 },
  ],
};

export const PRESENTATION_KPIS: MarketKPI[] = [
  {
    key: 'microMarkets',
    label: 'Tracked Micro-Markets',
    value: '342 Pockets',
    change: '+14.2% MoM',
    trend: 'up',
    description: 'Active commercial corridors with verified footfall',
  },
  {
    key: 'avgFootfall',
    label: 'Mean Footfall Quality',
    value: '8.7 / 10',
    change: '+4.5%',
    trend: 'up',
    description: 'Weighted pedestrian density across high streets',
  },
  {
    key: 'avgRent',
    label: 'National Median Rent',
    value: '₹112 / sqft',
    change: '-2.1%',
    trend: 'down',
    description: 'Prime retail ground-floor normalized benchmark',
  },
  {
    key: 'opportunityScore',
    label: 'Top Corridor Viability',
    value: '89.4%',
    change: '+6.8%',
    trend: 'up',
    description: 'Composite opportunity index across verified zones',
  },
];

export const DEMO_USERS: Record<string, UserSession> = {
  visitor: {
    id: 'user-guest',
    name: 'Guest Explorer',
    email: 'guest@vyaparmap.internal',
    role: 'visitor',
  },
  business_owner: {
    id: '000001',
    name: 'Abhinav Choudhary',
    email: 'Abhinav@gmail.com',
    role: 'business_owner',
    businessName: 'Atrix',
    businessType: 'Cafe',
    city: 'Jaipur',
  },
};

