import type { Franchise } from './m_schema';

/**
 * Additional Indian Franchise Opportunities
 */
export const ADDITIONAL_FRANCHISES: Franchise[] = [
  {
    id: 'fran-add-1',
    brand: 'Chai Sutta Bar',
    logoColor: '#E63946',
    category: 'Beverages & Snacks',
    investment: 850000,
    franchiseFee: 150000,
    royaltyPercent: 5,
    roiMonths: 12,
    outlets: 520,
    description: 'Youth-centric chai cafe chain served in traditional kulhads with immense viral brand recall and student footfall.',
    preferredLocations: ['Near Colleges', 'Transit Hubs', 'High Street'],
    minAreaSqft: 150,
    isOfficial: true,
    applyUrl: 'https://www.chaisuttabarindia.com/enquire-franchise/',
  },
  {
    id: 'fran-add-2',
    brand: 'Jawed Habib',
    logoColor: '#7C3AED',
    category: 'Salon & Grooming',
    investment: 1600000,
    franchiseFee: 250000,
    royaltyPercent: 6,
    roiMonths: 18,
    outlets: 1150,
    description: 'Premier Indian salon & wellness network. Certified stylists and trained staff provided directly by their academy.',
    preferredLocations: ['Residential Townships', 'Malls', 'Main Markets'],
    minAreaSqft: 300,
    isOfficial: true,
    applyUrl: 'https://jawedhabib.com/franchise/',
  },
  {
    id: 'fran-add-3',
    brand: 'DTDC Express',
    logoColor: '#059669',
    category: 'Logistics & Courier',
    investment: 250000,
    franchiseFee: 50000,
    royaltyPercent: 4,
    roiMonths: 8,
    outlets: 12500,
    description: 'Low-capital express courier and parcel logistics franchise with steady daily commercial B2B bookings.',
    preferredLocations: ['Commercial Markets', 'Industrial Areas', 'Residential Hubs'],
    minAreaSqft: 100,
    isOfficial: true,
  },
  {
    id: 'fran-add-4',
    brand: 'Amul Scooping Parlour',
    logoColor: '#0284C7',
    category: 'Ice Cream & Dairy',
    investment: 600000,
    franchiseFee: 50000,
    royaltyPercent: 0,
    roiMonths: 10,
    outlets: 8500,
    description: 'Zero royalty ice cream parlor model backed by trusted national brand equity and dairy cooperative distribution.',
    preferredLocations: ['High Street Corners', 'Near Schools/Parks', 'Market Squares'],
    minAreaSqft: 150,
    isOfficial: true,
  },
  {
    id: 'fran-add-5',
    brand: 'MBA Chai Wala',
    logoColor: '#D97706',
    category: 'Beverages & Snacks',
    investment: 1000000,
    franchiseFee: 200000,
    royaltyPercent: 5,
    roiMonths: 14,
    outlets: 150,
    description: 'High-energy tea cafe format with snack pairings, street-style ambiance, and loyal collegiate following.',
    preferredLocations: ['University Hubs', 'Food Streets', 'Commercial High Streets'],
    minAreaSqft: 200,
    isOfficial: true,
  },
  {
    id: 'fran-add-6',
    brand: "Giani's Ice Cream",
    logoColor: '#BE185D',
    category: 'Desserts & Ice Cream',
    investment: 1400000,
    franchiseFee: 200000,
    royaltyPercent: 5,
    roiMonths: 14,
    outlets: 250,
    description: 'Heritage Indian dessert parlour legendary for rabri faluda, sundaes, stone sundaes, and gourmet ice cream.',
    preferredLocations: ['High Footfall Markets', 'Night Food Squares', 'Residential Corridors'],
    minAreaSqft: 250,
    isOfficial: true,
  },
];

// Alias for backwards compatibility
export const MOCK_FRANCHISES = ADDITIONAL_FRANCHISES;

