/**
 * Dedicated Database for Government MSME Schemes & District Benchmarks
 */

import type { GovMsmeScheme, DistrictMsmeStats } from '@/types/schema';

export const GOV_DATA_FLAGS = {
  USE_MOCK_FALLBACK: true,
  PRIORITIZE_ACTUAL: true,
};

export const OFFICIAL_GOV_MSME_SCHEMES: GovMsmeScheme[] = [
  {
    id: 'pmegp',
    code: 'PMEGP',
    name: "Prime Minister's Employment Generation Programme",
    ministry: 'Ministry of MSME & KVIC',
    maxAssistance: 'Up to ₹50 Lakhs (Mfg) / ₹20 Lakhs (Service/Retail)',
    subsidyRate: '15% to 35% Direct Government Capital Subsidy',
    promoterContribution: '5% to 10% of total project cost',
    collateralRequirement: 'Zero (Guaranteed under CGTMSE)',
    eligibility: 'Any individual aged 18+ with minimum 8th pass qualification.',
    benefitSummary:
      'Govt pays 15% (urban general) to 35% (special categories/rural) of your project cost as a non-repayable capital grant.',
    officialPortalUrl: 'https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp',
    keyFeatures: [
      'Non-repayable capital margin grant deposited into bank after 3-year audit',
      'Available across commercial banks, RRBs, and Co-operative banks',
      'Direct integration with JanSamarth unified government loan portal',
      'Covers plant machinery, interior fit-outs, and working capital cycle',
    ],
  },
  {
    id: 'mudra',
    code: 'PMMY',
    name: 'Pradhan Mantri Mudra Yojana (MUDRA)',
    ministry: 'Ministry of Finance & Department of Financial Services',
    maxAssistance: 'Up to ₹20 Lakhs (Tarun Plus Category)',
    subsidyRate: 'Interest Subvention & Priority Rate Processing',
    promoterContribution: 'Nil up to ₹50,000; 10% to 15% for Kishore/Tarun',
    collateralRequirement: 'Zero Collateral Required by Law',
    eligibility: 'Non-corporate small business operators, shopkeepers, artisans, and service entrepreneurs.',
    benefitSummary:
      'Zero-collateral institutional bank loans divided into Shishu (<₹50K), Kishore (₹50K-₹5L), and Tarun (₹5L-₹20L).',
    officialPortalUrl: 'https://www.mudra.org.in/',
    keyFeatures: [
      'No third-party mortgage or asset pledging required',
      'Mudra Debit Card issued for real-time working capital withdrawals',
      'Nominal processing fees and competitive RBI benchmarked rates',
      'Covers transport vehicles, retail shops, food stalls, and repair workshops',
    ],
  },
  {
    id: 'cgtmse',
    code: 'CGTMSE',
    name: 'Credit Guarantee Fund Trust for Micro and Small Enterprises',
    ministry: 'Ministry of MSME & SIDBI',
    maxAssistance: 'Up to ₹500 Lakhs (₹5 Crores)',
    subsidyRate: '75% to 85% Sovereign Credit Guarantee Coverage',
    promoterContribution: '15% to 25% promoter equity',
    collateralRequirement: '100% Collateral-Free / Third-Party Guarantee Free',
    eligibility: 'New and existing Micro and Small enterprises in retail, trade, manufacturing, and services.',
    benefitSummary:
      'The Govt of India guarantees up to 85% of your bank loan default risk, enabling banks to lend without collateral.',
    officialPortalUrl: 'https://www.cgtmse.in/',
    keyFeatures: [
      'Allows first-time founders to secure large store leases and inventory credit',
      'Hybrid security model allows combining commercial mortgage with guarantee',
      'Concession in guarantee fee for women and aspirational district entrepreneurs',
      'Backed jointly by Ministry of MSME and SIDBI',
    ],
  },
  {
    id: 'standup_india',
    code: 'STANDUP',
    name: 'Stand-Up India Scheme for Greenfield Enterprises',
    ministry: 'Ministry of Finance & Department of Financial Services',
    maxAssistance: '₹10 Lakhs to ₹100 Lakhs (₹1 Crore)',
    subsidyRate: 'Low Interest Composite Term Loan + Working Capital',
    promoterContribution: '10% to 15% of project cost',
    collateralRequirement: 'Collateral-free or Credit Guarantee via NCGTC',
    eligibility: 'At least one SC/ST or Woman entrepreneur per bank branch for a new greenfield enterprise.',
    benefitSummary:
      'Bank credit for women and SC/ST founders setting up retail, trading, manufacturing, or service ventures.',
    officialPortalUrl: 'https://www.standupmitra.in/',
    keyFeatures: [
      'Composite loan covering both Capex (lease/fitout) and Opex (inventory/staff)',
      'Direct handholding support via Lead District Managers (LDM)',
      'Convergence with state-sponsored entrepreneurship subsidies',
      'Repayable over 7 years with a 18-month moratorium period',
    ],
  },
  {
    id: 'udyam_registration',
    code: 'UDYAM',
    name: 'Udyam National MSME Registration Framework',
    ministry: 'Ministry of MSME, Govt. of India',
    maxAssistance: 'Statutory MSME Classification & Priority Sector Benefits',
    subsidyRate: '1% Interest Subvention + 50% Patent/Trademark Rebate',
    promoterContribution: 'Zero (100% Free Government Registration)',
    collateralRequirement: 'Not Applicable',
    eligibility: 'All Indian retail traders, wholesale stores, and manufacturing/service enterprises.',
    benefitSummary:
      'Official permanent digital certificate with QR code unlocking priority bank lending, lower interest, and tax rebates.',
    officialPortalUrl: 'https://udyamregistration.gov.in/',
    keyFeatures: [
      'Paperless, zero-fee self-declaration registration with Aadhaar and PAN',
      'Qualifies retail stores for RBI Priority Sector Lending (PSL) interest discounts',
      'Statutory protection under MSME Samadhaan Act against buyers delaying payment past 45 days',
      'Concessional electricity tariffs and electricity duty waivers in participating states',
    ],
  },
];

export const OFFICIAL_DISTRICT_MSME_DATA: Record<string, DistrictMsmeStats> = {
  jaipur: {
    district: 'Jaipur',
    state: 'Rajasthan',
    totalRegisteredMsmes: 142850,
    microCount: 136210,
    smallCount: 6140,
    mediumCount: 500,
    topClusters: ['Gems & Jewelry', 'Heritage Tourism & Cafes', 'Handicrafts & Textiles', 'IT & BPO'],
    urbanCpiInflationIndex: 182.4,
    monthlyPerCapitaSpendingUrban: 5840,
    commercialElectricityRatePerUnit: 7.85,
    priorityLendingInterestDiscount: '1.00% p.a.',
    yearlyGrowth: [
      { year: '2021', count: 68400, growthRatePct: 24.2 },
      { year: '2022', count: 86500, growthRatePct: 26.4 },
      { year: '2023', count: 108900, growthRatePct: 25.8 },
      { year: '2024', count: 129400, growthRatePct: 18.8 },
      { year: '2025/26', count: 142850, growthRatePct: 10.4 },
    ],
    sectorDistribution: {
      retailTradePct: 44,
      servicesPct: 32,
      manufacturingPct: 18,
      agroProcessingPct: 6,
    },
    districtCategory: 'State Capital Commercial & Craft Hub',
    estimatedEmployment: 582400,
  },
  sanganer: {
    district: 'Jaipur (Sanganer Tehsil)',
    state: 'Rajasthan',
    totalRegisteredMsmes: 38400,
    microCount: 36800,
    smallCount: 1480,
    mediumCount: 120,
    topClusters: [
      'Handcrafted Mojari & Footwear Cluster',
      'Sanganeri Handblock Textile Printing',
      'Handmade Paper Fabrication',
      'Leather Goods Workshop',
    ],
    urbanCpiInflationIndex: 181.8,
    monthlyPerCapitaSpendingUrban: 5420,
    commercialElectricityRatePerUnit: 7.85,
    priorityLendingInterestDiscount: '1.00% p.a. (MoSJE Subvention)',
    yearlyGrowth: [
      { year: '2021', count: 18200, growthRatePct: 21.0 },
      { year: '2022', count: 22800, growthRatePct: 25.2 },
      { year: '2023', count: 28900, growthRatePct: 26.7 },
      { year: '2024', count: 34500, growthRatePct: 19.3 },
      { year: '2025/26', count: 38400, growthRatePct: 11.3 },
    ],
    sectorDistribution: {
      retailTradePct: 35,
      servicesPct: 22,
      manufacturingPct: 38,
      agroProcessingPct: 5,
    },
    districtCategory: 'Artisan & Footwear Manufacturing Cluster',
    estimatedEmployment: 154000,
  },
  chomu: {
    district: 'Jaipur Rural (Chomu Mandi)',
    state: 'Rajasthan',
    totalRegisteredMsmes: 28600,
    microCount: 27400,
    smallCount: 1120,
    mediumCount: 80,
    topClusters: [
      'Krishi Upaj Mandi & Grain Trade',
      'Mustard Oil Milling & Extraction',
      'Spices & Cold Storage Warehousing',
      'Dairy & Cattle Feed Processing',
    ],
    urbanCpiInflationIndex: 180.5,
    monthlyPerCapitaSpendingUrban: 4950,
    commercialElectricityRatePerUnit: 7.85,
    priorityLendingInterestDiscount: '1.00% p.a. (Priority Lending)',
    yearlyGrowth: [
      { year: '2021', count: 12400, growthRatePct: 19.5 },
      { year: '2022', count: 16100, growthRatePct: 29.8 },
      { year: '2023', count: 20800, growthRatePct: 29.1 },
      { year: '2024', count: 25400, growthRatePct: 22.1 },
      { year: '2025/26', count: 28600, growthRatePct: 12.6 },
    ],
    sectorDistribution: {
      retailTradePct: 40,
      servicesPct: 18,
      manufacturingPct: 16,
      agroProcessingPct: 26,
    },
    districtCategory: 'Agro-Mandi & Rural Processing Corridor',
    estimatedEmployment: 98000,
  },
  bengaluru: {
    district: 'Bangalore Urban',
    state: 'Karnataka',
    totalRegisteredMsmes: 286420,
    microCount: 268900,
    smallCount: 16120,
    mediumCount: 1400,
    topClusters: ['Tech & Electronics', 'Specialty Coffee & Dining', 'Logistics & Quick Commerce', 'Fintech'],
    urbanCpiInflationIndex: 178.6,
    monthlyPerCapitaSpendingUrban: 8250,
    commercialElectricityRatePerUnit: 8.20,
    priorityLendingInterestDiscount: '0.75% to 1.25% p.a.',
    yearlyGrowth: [
      { year: '2021', count: 128000, growthRatePct: 28.0 },
      { year: '2022', count: 168000, growthRatePct: 31.2 },
      { year: '2023', count: 215000, growthRatePct: 27.9 },
      { year: '2024', count: 258000, growthRatePct: 20.0 },
      { year: '2025/26', count: 286420, growthRatePct: 11.0 },
    ],
    sectorDistribution: {
      retailTradePct: 36,
      servicesPct: 45,
      manufacturingPct: 16,
      agroProcessingPct: 3,
    },
    districtCategory: 'High-Tech Mega Metro Hub',
    estimatedEmployment: 1450000,
  },
  delhi: {
    district: 'Central & South Delhi',
    state: 'Delhi NCR',
    totalRegisteredMsmes: 215680,
    microCount: 201240,
    smallCount: 13440,
    mediumCount: 1000,
    topClusters: ['Wholesale Merchandising', 'Fast Casual F&B', 'Apparel & Fashion', 'Electronics Retail'],
    urbanCpiInflationIndex: 180.1,
    monthlyPerCapitaSpendingUrban: 7620,
    commercialElectricityRatePerUnit: 8.50,
    priorityLendingInterestDiscount: '1.00% p.a.',
    yearlyGrowth: [
      { year: '2021', count: 104000, growthRatePct: 22.0 },
      { year: '2022', count: 134000, growthRatePct: 28.8 },
      { year: '2023', count: 168000, growthRatePct: 25.3 },
      { year: '2024', count: 196000, growthRatePct: 16.6 },
      { year: '2025/26', count: 215680, growthRatePct: 10.0 },
    ],
    sectorDistribution: {
      retailTradePct: 48,
      servicesPct: 38,
      manufacturingPct: 12,
      agroProcessingPct: 2,
    },
    districtCategory: 'National Capital Commercial Hub',
    estimatedEmployment: 1120000,
  },
  mumbai: {
    district: 'Mumbai & Mumbai Suburban',
    state: 'Maharashtra',
    totalRegisteredMsmes: 345290,
    microCount: 324020,
    smallCount: 19570,
    mediumCount: 1700,
    topClusters: ['F&B & Hospitality', 'Retail Fashion & Jewelry', 'Financial & Legal Tech', 'Logistics'],
    urbanCpiInflationIndex: 184.2,
    monthlyPerCapitaSpendingUrban: 7890,
    commercialElectricityRatePerUnit: 9.10,
    priorityLendingInterestDiscount: '1.00% p.a.',
    yearlyGrowth: [
      { year: '2021', count: 155000, growthRatePct: 25.0 },
      { year: '2022', count: 202000, growthRatePct: 30.3 },
      { year: '2023', count: 258000, growthRatePct: 27.7 },
      { year: '2024', count: 312000, growthRatePct: 20.9 },
      { year: '2025/26', count: 345290, growthRatePct: 10.6 },
    ],
    sectorDistribution: {
      retailTradePct: 44,
      servicesPct: 42,
      manufacturingPct: 13,
      agroProcessingPct: 1,
    },
    districtCategory: 'Financial Capital Commercial Zone',
    estimatedEmployment: 1890000,
  },
  pune: {
    district: 'Pune',
    state: 'Maharashtra',
    totalRegisteredMsmes: 194360,
    microCount: 182560,
    smallCount: 10800,
    mediumCount: 1000,
    topClusters: ['Auto Ancillary & EV', 'Student Cafes & Bakeries', 'Education & Coaching', 'IT Hardware'],
    urbanCpiInflationIndex: 179.8,
    monthlyPerCapitaSpendingUrban: 6940,
    commercialElectricityRatePerUnit: 8.40,
    priorityLendingInterestDiscount: '1.00% p.a.',
    yearlyGrowth: [
      { year: '2021', count: 88000, growthRatePct: 24.0 },
      { year: '2022', count: 114000, growthRatePct: 29.5 },
      { year: '2023', count: 145000, growthRatePct: 27.1 },
      { year: '2024', count: 174000, growthRatePct: 20.0 },
      { year: '2025/26', count: 194360, growthRatePct: 11.7 },
    ],
    sectorDistribution: {
      retailTradePct: 38,
      servicesPct: 36,
      manufacturingPct: 22,
      agroProcessingPct: 4,
    },
    districtCategory: 'Industrial & Student Metro Hub',
    estimatedEmployment: 840000,
  },
  chennai: {
    district: 'Chennai',
    state: 'Tamil Nadu',
    totalRegisteredMsmes: 188740,
    microCount: 176210,
    smallCount: 11530,
    mediumCount: 1000,
    topClusters: ['Automotive & Spares', 'Healthcare & Pharmacy', 'Textile Retailing', 'Software Services'],
    urbanCpiInflationIndex: 181.3,
    monthlyPerCapitaSpendingUrban: 6780,
    commercialElectricityRatePerUnit: 8.00,
    priorityLendingInterestDiscount: '0.85% to 1.15% p.a.',
    yearlyGrowth: [
      { year: '2021', count: 84000, growthRatePct: 22.0 },
      { year: '2022', count: 110000, growthRatePct: 30.9 },
      { year: '2023', count: 141000, growthRatePct: 28.1 },
      { year: '2024', count: 169000, growthRatePct: 19.8 },
      { year: '2025/26', count: 188740, growthRatePct: 11.6 },
    ],
    sectorDistribution: {
      retailTradePct: 41,
      servicesPct: 37,
      manufacturingPct: 19,
      agroProcessingPct: 3,
    },
    districtCategory: 'Automotive & Port Trade Hub',
    estimatedEmployment: 790000,
  },
  hyderabad: {
    district: 'Hyderabad',
    state: 'Telangana',
    totalRegisteredMsmes: 172900,
    microCount: 161400,
    smallCount: 10500,
    mediumCount: 1000,
    topClusters: ['Pharma & Life Sciences', 'IT Corridors', 'Specialty Dining & Biryani Chains', 'Hardware Trade'],
    urbanCpiInflationIndex: 179.2,
    monthlyPerCapitaSpendingUrban: 7150,
    commercialElectricityRatePerUnit: 8.15,
    priorityLendingInterestDiscount: '1.00% p.a.',
    yearlyGrowth: [
      { year: '2021', count: 76000, growthRatePct: 26.0 },
      { year: '2022', count: 101000, growthRatePct: 32.8 },
      { year: '2023', count: 130000, growthRatePct: 28.7 },
      { year: '2024', count: 156000, growthRatePct: 20.0 },
      { year: '2025/26', count: 172900, growthRatePct: 10.8 },
    ],
    sectorDistribution: {
      retailTradePct: 40,
      servicesPct: 41,
      manufacturingPct: 16,
      agroProcessingPct: 3,
    },
    districtCategory: 'IT & Commercial Expansion Hub',
    estimatedEmployment: 760000,
  },
  varanasi: {
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    totalRegisteredMsmes: 94200,
    microCount: 90150,
    smallCount: 3700,
    mediumCount: 350,
    topClusters: [
      'Banarasi Silk & Brocade Handloom',
      'Wooden Lacquerware & Toys',
      'Brassware & Metal Repousse',
      'Heritage Tourism & Sweets',
    ],
    urbanCpiInflationIndex: 183.1,
    monthlyPerCapitaSpendingUrban: 5120,
    commercialElectricityRatePerUnit: 7.90,
    priorityLendingInterestDiscount: '1.00% p.a.',
    yearlyGrowth: [
      { year: '2021', count: 42000, growthRatePct: 22.0 },
      { year: '2022', count: 54000, growthRatePct: 28.5 },
      { year: '2023', count: 69000, growthRatePct: 27.7 },
      { year: '2024', count: 84000, growthRatePct: 21.7 },
      { year: '2025/26', count: 94200, growthRatePct: 12.1 },
    ],
    sectorDistribution: {
      retailTradePct: 39,
      servicesPct: 25,
      manufacturingPct: 31,
      agroProcessingPct: 5,
    },
    districtCategory: 'Heritage Handloom & Craft Cluster',
    estimatedEmployment: 395000,
  },
};

